In [1]:
import pandas as pd
import numpy as np

In [2]:
# https://www.kaggle.com/datasets/saife245/english-premier-league?select=Datasets

In [3]:
# Key to results data:

# Div = League Division
# Date = Match Date (dd/mm/yy)
# Time = Time of match kick-off
# HomeTeam = Home Team
# Away team = Away Team
# FTHG and HG = Full Time Home Team Goals
# FTAG and AG = Full-Time Away Team Goals
# FTR and Res = Full-Time Result (H=Home Win, D=Draw, A=Away Win)
# HTHG = Half Time Home Team Goals
# HTAG = Half Time Away Team Goals
# HTR = Half Time Result (H=Home Win, D=Draw, A=Away Win)

# Match Statistics (where available)
# Attendance = Crowd Attendance
# Referee = Match Referee
# HS = Home Team Shots
# AS = Away Team Shots
# HST = Home Team Shots on Target
# AST = Away Team Shots on Target
# HHW = Home Team Hit Woodwork
# AHW = Away Team Hit Woodwork
# HC = Home Team Corners
# AC = Away Team Corners
# HF = Home Team Fouls Committed
# AF = Away Team Fouls Committed
# HFKC = Home Team Free Kicks Conceded
# AFKC = Away Team Free Kicks Conceded
# HO = Home Team Offsides
# AO = Away Team Offsides
# HY = Home Team Yellow Cards
# AY = Away Team Yellow Cards
# HR = Home Team Red Cards
# AR = Away Team Red Cards

In [4]:
pd.set_option('display.max_columns', None)

# Taking a look at my data

In [5]:
y0001 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2000-01.csv')

In [6]:
y0102 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2001-02.csv')

In [7]:
y0203 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2002-03.csv')

In [8]:
y0304 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2003-04.csv')

In [9]:
y0405 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2004-05.csv')

In [10]:
y0506 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2005-06.csv')

In [11]:
y0607 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2006-07.csv')

In [12]:
y0708 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2007-08.csv')

In [13]:
y0809 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2008-09.csv')

In [14]:
y0910 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2009-10.csv')

In [15]:
y1011 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2010-11.csv')

In [16]:
y1112 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2011-12.csv')

In [17]:
y1213 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2012-13.csv')

In [18]:
y1314 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2013-14.csv')

In [19]:
y1415 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2014-15.csv')

In [20]:
y1516 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/Datasets/2015-16.csv')

In [21]:
import datetime as dt
y1617 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/datanobets/2016-2017.csv')
y1617
# y1617['year'] = pd.DatetimeIndex(y1617['Date']).year
# y1617.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,J Moss,10,17,3,9,10,14,7,4,3,2,0,0
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,C Pawson,14,13,4,3,12,15,3,6,2,2,0,0
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,M Atkinson,12,13,6,4,10,14,5,6,0,0,0,0
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,M Dean,14,18,5,5,8,17,5,3,2,2,0,0
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,R Madley,16,7,4,3,11,14,9,6,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,21/05/17,Liverpool,Middlesbrough,3,0,H,1,0,H,M Atkinson,25,9,10,3,13,8,3,3,0,1,0,0
376,E0,21/05/17,Man United,Crystal Palace,2,0,H,2,0,H,A Taylor,9,6,2,1,16,10,3,6,2,0,0,0
377,E0,21/05/17,Southampton,Stoke,0,1,A,0,0,D,L Probert,14,14,6,3,12,10,4,10,2,4,0,0
378,E0,21/05/17,Swansea,West Brom,2,1,H,0,1,A,M Dean,12,16,2,5,8,10,7,4,1,1,0,0
379,E0,21/05/17,Watford,Man City,0,5,A,0,4,A,J Moss,6,15,3,9,12,10,4,5,1,0,0,0

In [22]:
y1718 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/datanobets/2017-2018.csv')

In [23]:
y1819 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/datanobets/2018-2019.csv')

In [24]:
y1920 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/datanobets/2019-2020.csv')

In [25]:
y2021 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/datanobets/2020-2021.csv')

In [26]:
y2122 = pd.read_csv('/Users/lucaalfano/IH-labs/Project/archive/datanobets/2021-2022.csv')

# What can i do with this?

In [27]:
# drop betting columns from newer datasets
# i dont think i will use them at all 
# 
# make an average table position out of eplstandings?
# use this average table position in some way?
# 
# 
# 
# make dfs with same columns, dropping betting odds 
# concat ?

# group by hometeam agg func home goals sum

In [28]:
# make a function to keep certain columns and drop the rest, axis=0 to concat on top of eachother ?

In [29]:
# columnsreq = ['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
#  'HC', 'AC', 'HY', 'AY', 'HR', 'AR']

In [30]:
list(y1617.columns.values.tolist())

['Div',
 'Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR']

In [31]:
# columns ['Date', 'HomeTeam', 'AwayTeam', 'FTHG','FTAG','FTR','HTHG','HTAG','HS','AS','HST','AST',
#  'HF', 'AF','HC','AC','HY','AY','HR','AR']

In [32]:
# y1617 = y1617[columnsreq]

# pd.set_option('display.max_columns', None)

In [33]:
y1617

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,J Moss,10,17,3,9,10,14,7,4,3,2,0,0
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,C Pawson,14,13,4,3,12,15,3,6,2,2,0,0
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,M Atkinson,12,13,6,4,10,14,5,6,0,0,0,0
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,M Dean,14,18,5,5,8,17,5,3,2,2,0,0
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,R Madley,16,7,4,3,11,14,9,6,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,21/05/17,Liverpool,Middlesbrough,3,0,H,1,0,H,M Atkinson,25,9,10,3,13,8,3,3,0,1,0,0
376,E0,21/05/17,Man United,Crystal Palace,2,0,H,2,0,H,A Taylor,9,6,2,1,16,10,3,6,2,0,0,0
377,E0,21/05/17,Southampton,Stoke,0,1,A,0,0,D,L Probert,14,14,6,3,12,10,4,10,2,4,0,0
378,E0,21/05/17,Swansea,West Brom,2,1,H,0,1,A,M Dean,12,16,2,5,8,10,7,4,1,1,0,0
379,E0,21/05/17,Watford,Man City,0,5,A,0,4,A,J Moss,6,15,3,9,12,10,4,5,1,0,0,0

In [34]:
# get points from HTR? 3 points to home/ 1 each draw

In [35]:
# if fthg > ftag then 3 points home team elif ftag > fthg 3 points away else fthg = ftag 1 point each 
# split columns?

In [36]:
# the data set is big, 
# just use years 2016/17 - 21/22?
# y1617

In [37]:
# hometeamgames

In [38]:
# hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})

In [39]:
# hometeamgames

In [40]:
# homegamesresults = hometeamgames.groupby('HomeTeam').sum().reset_index()

In [41]:
# homegamesresults = homegamesresults.rename(columns={'FTHG':'HGS', 'FTAG':'HGC'})

In [42]:
# ratio of shots to goal ?

In [45]:
def bigfunc(df):

#     df['year'] = pd.DatetimeIndex(df['Date']).year

    # organizing, renaming cols, and attributing points to winner/home
    hometeamgames = df[['Date', 'HomeTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'HST', 'HF', 'HC', 'HY', 'HR']]
    
    hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
    
#     hometeamgames['year'] = pd.DatetimeIndex(df['Date']).year

    
    homewin = []
    homedraw = []
    homeloss = []
    
    for i in hometeamgames['FTR']:
        if 'A' in i:
            homewin.append(0)
            homedraw.append(0)
            homeloss.append(1)
        elif 'D' in i:
            homewin.append(0)
            homedraw.append(1)
            homeloss.append(0)
        elif 'H' in i:
            homewin.append(1)
            homedraw.append(0)
            homeloss.append(0)
    hometeamgames['homewin'] = homewin
    hometeamgames['homedraw'] = homedraw
    hometeamgames['homeloss'] = homeloss
    
    homegamesresults = hometeamgames.groupby('HomeTeam').sum().reset_index()

    homegamesresults = homegamesresults.rename(columns={'FTHG':'HGS', 'FTAG':'HGC'})
    
    homegamesresults['homeplayed'] = homegamesresults['homewin']+homegamesresults['homedraw']+homegamesresults['homeloss']
    
    
    
    
    
    # organizing, renaming cols, and attributing points to winner/away
    awayteamgames = df[['Date', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'AS', 'AST', 'AF', 'AC', 'AY', 'AR']]
    
    awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
    
    awaywin = []
    awaydraw = []
    awayloss = []
    
    for i in awayteamgames['FTR']:
        if 'A' in i:
            awaywin.append(1)
            awaydraw.append(0)
            awayloss.append(0)
        elif 'D' in i:
            awaywin.append(0)
            awaydraw.append(1)
            awayloss.append(0)
        elif 'H' in i:
            awaywin.append(0)
            awaydraw.append(0)
            awayloss.append(1)
    awayteamgames['awaywin'] = awaywin
    awayteamgames['awaydraw'] = awaydraw
    awayteamgames['awayloss'] = awayloss
        
    awaygamesresults = awayteamgames.groupby('AwayTeam').sum().reset_index()
    
    awaygamesresults = awaygamesresults.rename(columns={'FTHG':'AGC', 'FTAG':'AGS'})
    
    awaygamesresults['awayplayed'] = awaygamesresults['awaywin']+awaygamesresults['awaydraw']+awaygamesresults['awayloss']
    
    
    
    
    # back together to find season totals 
    seasonresults = pd.concat([homegamesresults, awaygamesresults], axis=1)
    
#     seasonresults['year'] = pd.DatetimeIndex(hometeamgames['Date']).year
    # agg cols 
    seasonresults['totalpoints'] = seasonresults['homepoints']+seasonresults['awaypoints']
    
    seasonresults['gamesplayed'] = seasonresults['homeplayed'] + seasonresults['awayplayed']
    
    seasonresults['TGS'] = seasonresults['HGS']+seasonresults['AGS']
    
    seasonresults['TGC'] = seasonresults['HGC']+seasonresults['AGC']
    
    seasonresults['GD'] = seasonresults['TGS']-seasonresults['TGC']

    seasonresults = seasonresults.rename(columns={'HomeTeam':'Team'})

    #ratios 
    
    seasonresults['winsagg'] = seasonresults['homewin']+seasonresults['awaywin']
    seasonresults['drawsagg'] = seasonresults['homedraw']+seasonresults['awaydraw']
    seasonresults['lossagg'] = seasonresults['homeloss']+seasonresults['awayloss']
    
#     seasonresults['win%'] = round((seasonresults['winsagg']/seasonresults['gamesplayed']*100),1)
#     seasonresults['draw%'] = round((seasonresults['drawsagg']/seasonresults['gamesplayed']*100),1)
#     seasonresults['loss%'] = round((seasonresults['lossagg']/seasonresults['gamesplayed']*100),1)

    seasonresults = seasonresults[['Team', 'HGS', 'HGC', 'AGS', 'AGC','HS', 'AS', 'HST', 'AST', 'HF','AF','HC','AC', 'HY', 'AY', 'HR', 'AR' , 'totalpoints', 'TGS', 'TGC', 'GD', 'homepoints', 'awaypoints', 'gamesplayed', 'homewin', 'homedraw', 'homeloss', 'awaywin', 'awaydraw', 'awayloss','winsagg','drawsagg','lossagg']]

    return seasonresults

In [46]:
sr1617=bigfunc(y1617)
sr1718=bigfunc(y1718)
sr1819=bigfunc(y1819)
sr1920=bigfunc(y1920)
sr2021=bigfunc(y2021)
sr2122=bigfunc(y2122)

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

In [47]:
y6list = [sr1617,sr1718,sr1819,sr1920,sr2021,sr2122]

In [48]:
y6 = pd.concat(y6list,axis=0).reset_index(drop=True)

In [49]:
pd.set_option('display.max_columns', None)

In [50]:
y6.groupby('Team').sum().reset_index()

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
0,Arsenal,230,114,166,167,1746,1335,641,463,1194,1127,763,549,191,198,9,12,394,396,281,115,242,152,228,74,20,20,43,23,48,117,43,68
1,Aston Villa,80,86,68,81,753,671,261,238,653,638,321,290,94,114,5,1,135,148,167,-19,72,63,114,20,12,25,18,9,30,38,21,55
2,Bournemouth,113,114,83,149,948,801,316,286,697,716,411,383,127,112,5,3,169,196,263,-67,107,62,152,29,20,27,16,14,46,45,34,73
3,Brentford,22,21,26,35,233,209,77,77,187,184,88,71,29,32,2,1,46,48,56,-8,24,22,38,7,3,9,6,4,9,13,7,18
4,Brighton,104,125,86,133,1228,958,339,324,1041,1040,525,393,158,128,5,11,209,190,258,-68,117,92,190,27,36,32,21,29,45,48,65,77
5,Burnley,122,144,108,176,1273,1034,413,338,1157,1168,542,441,183,205,0,5,262,230,320,-90,149,113,228,41,26,47,27,32,55,68,58,102
6,Cardiff,21,38,13,31,230,187,68,58,195,189,95,73,33,32,0,1,34,34,69,-35,20,14,38,6,2,11,4,2,13,10,4,24
7,Chelsea,222,101,191,132,1938,1629,719,546,1132,1192,788,591,154,179,5,3,442,413,233,180,233,209,228,69,26,19,63,20,31,132,46,50
8,Crystal Palace,134,144,134,189,1409,1132,450,383,1248,1281,612,508,190,198,2,5,269,268,333,-65,141,128,228,37,30,47,34,26,54,71,56,101
9,Everton,175,133,119,185,1442,1219,502,429,1248,1328,619,473,186,195,8,12,311,294,318,-24,193,118,228,56,25,33,30,28,56,86,53,89
10,Fulham,31,64,30,70,508,387,149,136,436,471,191,134,70,64,3,2,54,61,134,-73,31,23,76,8,7,23,4,11,23,12,18,46
11,Huddersfield,26,56,24,78,410,350,112,117,394,422,187,140,53,63,5,2,53,50,134,-84,32,21,76,8,8,22,4,9,25,12,17,47
12,Hull,28,35,9,45,208,188,69,58,219,184,73,106,32,35,2,3,34,37,80,-43,28,6,38,8,4,7,1,3,15,9,7,22
13,Leeds,47,59,57,74,529,478,182,171,463,433,214,188,86,75,2,2,97,104,133,-29,47,50,76,12,11,15,15,5,18,27,16,33
14,Leicester,183,137,169,184,1508,1317,533,488,1159,1198,653,578,150,185,5,10,323,352,321,31,187,136,228,55,22,37,36,28,50,91,50,87
15,Liverpool,275,83,223,120,2060,1720,762,634,1041,1105,819,712,110,153,2,3,508,498,203,295,274,234,228,84,22,8,69,27,18,153,49,26
16,Man City,313,88,252,94,2152,1892,802,672,1034,1075,900,813,140,181,7,7,536,565,182,383,279,257,228,88,15,11,81,14,19,169,29,30
17,Man United,207,113,176,135,1749,1451,662,569,1277,1337,676,561,193,231,4,6,414,383,248,135,220,194,228,62,34,18,55,29,30,117,63,48
18,Middlesbrough,17,23,10,30,205,144,59,41,210,268,93,48,38,38,0,1,28,27,53,-26,18,10,38,4,6,9,1,7,11,5,13,20
19,Newcastle,117,123,92,154,1194,939,384,329,1005,975,439,381,147,167,7,4,227,209,277,-68,132,95,190,36,24,35,24,23,48,60,47,83
20,Norwich,31,80,18,79,420,362,136,104,364,355,191,136,58,64,3,2,43,49,159,-110,27,16,76,7,6,25,3,7,28,10,13,53
21,Sheffield United,36,42,23,60,394,285,129,85,419,450,224,159,62,72,2,3,77,59,102,-43,49,28,76,15,4,19,6,10,22,21,14,41
22,Southampton,136,161,128,203,1513,1371,516,487,1240,1298,641,601,164,196,10,6,256,264,364,-100,139,117,228,35,34,45,29,30,55,64,64,100
23,Stoke,44,54,32,70,432,376,144,124,441,429,183,141,65,67,3,0,77,76,124,-48,47,30,76,12,11,15,6,12,20,18,23,35
24,Sunderland,16,34,13,35,214,173,66,55,221,216,86,74,35,41,2,2,24,29,69,-40,14,10,38,3,5,11,3,1,15,6,6,26
25,Swansea,44,58,29,68,437,289,152,98,386,392,214,132,54,53,0,1,74,73,126,-53,48,26,76,14,6,18,6,8,24,20,14,42
26,Tottenham,230,97,195,136,1774,1433,651,546,1216,1223,695,581,164,205,3,8,426,425,233,192,246,180,228,77,15,22,51,27,36,128,42,58
27,Watford,117,161,89,171,1151,962,361,313,1191,1124,435,419,200,155,10,9,188,206,332,-126,114,74,190,31,21,43,19,17,59,50,38,102
28,West Brom,63,90,46,93,604,511,196,153,654,639,281,198,94,109,2,3,102,109,183,-74,62,40,114,15,17,25,8,16,33,23,33,58
29,West Ham,170,165,148,182,1399,1229,473,441,1095,1108,580,489,194,171,2,13,299,318,347,-29,171,128,228,48,27,39,34,26,54,82,53,93
30,Wolves,96,90,76,91,994,803,316,270,798,807,405,360,123,118,1,4,212,172,181,-9,114,98,152,32,18,26,26,20,30,58,38,56

In [51]:
sr0001 = bigfunc(y0001)
sr0102 = bigfunc(y0102)
sr0203 = bigfunc(y0203)
sr0304 = bigfunc(y0304)
sr0405 = bigfunc(y0405)
sr0506 = bigfunc(y0506)
sr0607 = bigfunc(y0607)
sr0708 = bigfunc(y0708)
sr0809 = bigfunc(y0809)
sr0910 = bigfunc(y0910)
sr1011 = bigfunc(y1011)
sr1112 = bigfunc(y1112)
sr1213 = bigfunc(y1213)
sr1314 = bigfunc(y1314)
sr1415 = bigfunc(y1415)
sr1516 = bigfunc(y1516)
sr1617 = bigfunc(y1617)
sr1718 = bigfunc(y1718)
sr1819 = bigfunc(y1819)
sr1920 = bigfunc(y1920)
sr2021 = bigfunc(y2021)
sr2122 = bigfunc(y2122)

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_10530/1257642022.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

In [52]:
y20list = [sr0001,sr0102,sr0203,sr0304,sr0405,sr0506,sr0607,sr0708,sr0809,sr0910,sr1011,sr1112,sr1213,sr1314,sr1415,sr1516,sr1617,sr1718,sr1819,sr1920,sr2021,sr2122]

In [53]:
y20 = pd.concat(y20list,axis=0).reset_index(drop=True)

In [54]:
y20.groupby('Team').sum().reset_index()

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
0,Arsenal,892,367,669,509,6550,5114,3246,2434,4520,4601,3060,2183,580,712,25,49,1603,1561,876,685,929,674,836,281,86,51,189,107,122,470,193,173
1,Aston Villa,457,427,409,582,4289,3668,1942,1715,4267,4662,2214,1798,512,693,25,23,885,866,1009,-143,504,381,722,132,108,121,93,102,166,225,210,287
2,Birmingham,162,140,111,220,1365,1064,707,549,1634,1687,748,565,191,241,13,14,301,273,360,-87,196,105,266,50,46,37,23,36,74,73,82,111
3,Blackburn,289,239,229,353,2645,2000,1343,1047,2886,2848,1206,1036,342,411,23,27,530,518,592,-74,317,213,418,86,59,64,54,51,104,140,110,168
4,Blackpool,30,37,25,41,253,193,134,101,216,187,94,92,22,25,0,2,39,55,78,-23,20,19,38,5,5,9,5,4,10,10,9,19
5,Bolton,278,260,217,353,2787,2003,1546,1010,2617,2765,1288,970,296,428,17,19,506,495,613,-118,306,200,418,81,63,65,51,47,111,132,110,176
6,Bournemouth,136,148,105,182,1191,1021,399,347,872,903,540,475,152,139,5,4,211,241,330,-89,127,84,190,34,25,36,22,18,55,56,43,91
7,Bradford,20,29,10,41,221,150,101,73,255,262,108,71,27,30,0,1,26,30,70,-40,19,7,38,4,7,8,1,4,14,5,11,22
8,Brentford,22,21,26,35,233,209,77,77,187,184,88,71,29,32,2,1,46,48,56,-8,24,22,38,7,3,9,6,4,9,13,7,18
9,Brighton,104,125,86,133,1228,958,339,324,1041,1040,525,393,158,128,5,11,209,190,258,-68,117,92,190,27,36,32,21,29,45,48,65,77
10,Burnley,161,195,139,260,1721,1421,600,504,1576,1589,732,601,236,273,0,9,325,300,455,-155,194,131,304,52,38,62,31,38,83,83,76,145
11,Cardiff,41,73,25,70,458,378,142,110,362,364,205,159,58,56,0,2,64,66,143,-77,40,24,76,11,7,20,6,6,26,17,13,46
12,Charlton,179,178,122,208,1436,1087,772,552,1639,1644,731,619,158,180,13,8,325,301,386,-85,195,130,266,54,33,46,31,37,65,85,70,111
13,Chelsea,872,338,666,419,6856,5676,3167,2549,4538,4737,2831,2350,555,759,24,37,1665,1538,757,781,918,747,836,274,96,48,218,93,107,492,189,155
14,Coventry,14,23,22,40,213,176,95,82,247,282,127,79,25,51,3,1,34,36,63,-27,19,15,38,4,7,8,4,3,12,8,10,20
15,Crystal Palace,213,236,215,309,2323,1878,797,652,2177,2274,1044,865,301,324,7,10,437,428,545,-117,233,204,380,63,44,83,52,48,90,115,92,173
16,Derby,55,93,35,118,536,398,257,205,769,788,268,209,97,114,2,4,83,90,211,-121,58,25,114,14,16,27,5,10,42,19,26,69
17,Everton,656,459,446,600,5558,4334,2551,1983,4866,5158,2590,1987,601,691,33,41,1191,1102,1059,43,725,466,836,207,104,107,114,124,180,321,228,287
18,Fulham,380,363,251,468,3433,2678,1698,1281,3247,3438,1531,1202,380,461,23,18,640,631,831,-200,423,217,570,120,63,102,42,91,152,162,154,254
19,Huddersfield,26,56,24,78,410,350,112,117,394,422,187,140,53,63,5,2,53,50,134,-84,32,21,76,8,8,22,4,9,25,12,17,47
20,Hull,107,145,74,178,1106,896,438,343,1180,1148,459,388,143,187,12,12,171,181,323,-142,111,60,190,29,24,42,12,24,59,41,48,101
21,Ipswich,51,39,47,67,528,365,261,154,382,478,268,162,25,47,1,2,102,98,106,-8,60,42,76,17,9,12,12,6,20,29,15,32
22,Leeds,164,158,155,191,1548,1179,665,542,1594,1574,718,546,206,241,6,13,311,319,349,-30,162,149,228,44,30,40,43,20,51,87,50,91
23,Leicester,308,262,275,330,2649,2152,1022,848,2282,2421,1199,1019,266,357,13,23,554,583,592,-9,324,230,418,90,54,65,60,50,99,150,104,164
24,Liverpool,846,319,670,489,7197,5565,3230,2581,4225,4688,3073,2379,416,672,16,29,1591,1516,808,708,904,687,836,267,103,48,197,96,125,464,199,173
25,Man City,845,364,633,482,6310,5305,2882,2352,4296,4568,2934,2280,503,718,25,38,1440,1478,846,632,821,619,798,252,65,82,176,91,132,428,156,214
26,Man United,874,328,688,454,6797,5290,3295,2564,4539,4830,2889,2351,554,752,14,37,1698,1562,782,780,941,757,836,289,74,55,218,103,97,507,177,152
27,Middlesbrough,251,232,163,271,2236,1697,1117,838,2314,2563,1071,732,272,344,12,20,432,414,503,-89,270,162,380,71,57,62,36,54,100,107,111,162
28,Newcastle,552,463,391,637,5101,3693,2330,1677,4436,4464,2243,1679,535,673,27,45,973,943,1100,-157,608,365,760,170,98,112,90,95,195,260,193,307
29,Norwich,156,210,95,279,1606,1267,663,489,1403,1455,689,550,189,209,7,9,234,251,489,-238,158,76,266,41,35,57,15,31,87,56,66,144
30,Portsmouth,184,159,108,221,1826,1230,988,628,1691,1756,839,560,194,217,12,8,302,292,380,-88,196,106,266,54,34,45,25,31,77,79,65,122
31,QPR,60,77,55,122,843,649,356,304,602,618,285,259,87,104,9,6,92,115,199,-84,63,29,114,15,18,24,7,8,42,22,26,66
32,Reading,71,78,65,108,570,503,297,243,583,634,382,325,65,81,5,4,119,136,186,-50,81,38,114,23,12,22,9,11,37,32,23,59
33,Sheffield United,60,63,31,94,620,461,251,165,646,678,345,218,93,109,2,5,115,91,157,-66,76,39,114,22,10,25,9,12,36,31,22,61
34,Southampton,399,350,299,453,3797,3188,1520,1275,3285,3460,1629,1466,365,442,25,17,704,698,803,-105,417,287,570,111,84,90,70,77,138,181,161,228
35,Stoke,248,213,150,312,2181,1700,854,646,2191,2278,1002,710,317,371,14,16,457,398,525,-127,297,160,380,81,54,55,35,55,100,116,109,155
36,Sunderland,288,336,232,459,3206,2484,1476,1139,3211,3327,1437,1114,448,522,17,34,520,520,795,-275,318,202,532,81,75,110,46,64,156,127,139,266
37,Swansea,179,170,127,213,1647,1317,678,521,1280,1357,724,557,188,182,6,8,312,306,383,-77,190,122,266,51,37,45,31,29,73,82,66,118
38,Tottenham,758,425,565,586,6430,4850,3055,2270,4604,4748,2727,2141,555,722,19,39,1370,1323,1011,312,822,548,836,245,87,86,148,104,166,393,191,252
39,Watford,156,205,119,236,1594,1308,529,453,1666,1671,643,588,261,216,13,11,261,275,441,-166,156,105,266,40,36,57,27,24,82,67,60,139
40,West Brom,295,361,215,411,2934,2428,1279,1043,2788,2859,1358,1042,359,410,13,22,490,510,772,-262,294,196,494,76,66,105,41,73,133,117,139,238
41,West Ham,520,472,388,588,4638,3713,2019,1565,4071,4087,2062,1672,561,652,17,36,895,908,1060,-152,538,357,722,150,88,123,88,93,180,238,181,303
42,Wigan,169,215,147,267,1986,1602,1024,841,1804,1886,870,638,229,289,9,18,331,316,482,-166,189,142,304,48,45,59,37,31,84,85,76,143
43,Wolves,181,220,147,242,1866,1488,792,627,1618,1715,860,737,234,264,6,11,348,328,462,-134,201,147,304,55,36,61,35,42,75,90,78,136

In [55]:
y20 = y20.groupby('Team').sum().reset_index()

In [56]:
# seasonresults = seasonresults.sort_values(['Points'], axis = 0, ascending = False).reset_index(drop=True)
y20.sort_values(["totalpoints"],axis=0,ascending=False)

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
26,Man United,874,328,688,454,6797,5290,3295,2564,4539,4830,2889,2351,554,752,14,37,1698,1562,782,780,941,757,836,289,74,55,218,103,97,507,177,152
13,Chelsea,872,338,666,419,6856,5676,3167,2549,4538,4737,2831,2350,555,759,24,37,1665,1538,757,781,918,747,836,274,96,48,218,93,107,492,189,155
0,Arsenal,892,367,669,509,6550,5114,3246,2434,4520,4601,3060,2183,580,712,25,49,1603,1561,876,685,929,674,836,281,86,51,189,107,122,470,193,173
24,Liverpool,846,319,670,489,7197,5565,3230,2581,4225,4688,3073,2379,416,672,16,29,1591,1516,808,708,904,687,836,267,103,48,197,96,125,464,199,173
25,Man City,845,364,633,482,6310,5305,2882,2352,4296,4568,2934,2280,503,718,25,38,1440,1478,846,632,821,619,798,252,65,82,176,91,132,428,156,214
38,Tottenham,758,425,565,586,6430,4850,3055,2270,4604,4748,2727,2141,555,722,19,39,1370,1323,1011,312,822,548,836,245,87,86,148,104,166,393,191,252
17,Everton,656,459,446,600,5558,4334,2551,1983,4866,5158,2590,1987,601,691,33,41,1191,1102,1059,43,725,466,836,207,104,107,114,124,180,321,228,287
28,Newcastle,552,463,391,637,5101,3693,2330,1677,4436,4464,2243,1679,535,673,27,45,973,943,1100,-157,608,365,760,170,98,112,90,95,195,260,193,307
41,West Ham,520,472,388,588,4638,3713,2019,1565,4071,4087,2062,1672,561,652,17,36,895,908,1060,-152,538,357,722,150,88,123,88,93,180,238,181,303
1,Aston Villa,457,427,409,582,4289,3668,1942,1715,4267,4662,2214,1798,512,693,25,23,885,866,1009,-143,504,381,722,132,108,121,93,102,166,225,210,287
34,Southampton,399,350,299,453,3797,3188,1520,1275,3285,3460,1629,1466,365,442,25,17,704,698,803,-105,417,287,570,111,84,90,70,77,138,181,161,228
18,Fulham,380,363,251,468,3433,2678,1698,1281,3247,3438,1531,1202,380,461,23,18,640,631,831,-200,423,217,570,120,63,102,42,91,152,162,154,254
23,Leicester,308,262,275,330,2649,2152,1022,848,2282,2421,1199,1019,266,357,13,23,554,583,592,-9,324,230,418,90,54,65,60,50,99,150,104,164
3,Blackburn,289,239,229,353,2645,2000,1343,1047,2886,2848,1206,1036,342,411,23,27,530,518,592,-74,317,213,418,86,59,64,54,51,104,140,110,168
36,Sunderland,288,336,232,459,3206,2484,1476,1139,3211,3327,1437,1114,448,522,17,34,520,520,795,-275,318,202,532,81,75,110,46,64,156,127,139,266
5,Bolton,278,260,217,353,2787,2003,1546,1010,2617,2765,1288,970,296,428,17,19,506,495,613,-118,306,200,418,81,63,65,51,47,111,132,110,176
40,West Brom,295,361,215,411,2934,2428,1279,1043,2788,2859,1358,1042,359,410,13,22,490,510,772,-262,294,196,494,76,66,105,41,73,133,117,139,238
35,Stoke,248,213,150,312,2181,1700,854,646,2191,2278,1002,710,317,371,14,16,457,398,525,-127,297,160,380,81,54,55,35,55,100,116,109,155
15,Crystal Palace,213,236,215,309,2323,1878,797,652,2177,2274,1044,865,301,324,7,10,437,428,545,-117,233,204,380,63,44,83,52,48,90,115,92,173
27,Middlesbrough,251,232,163,271,2236,1697,1117,838,2314,2563,1071,732,272,344,12,20,432,414,503,-89,270,162,380,71,57,62,36,54,100,107,111,162
43,Wolves,181,220,147,242,1866,1488,792,627,1618,1715,860,737,234,264,6,11,348,328,462,-134,201,147,304,55,36,61,35,42,75,90,78,136
42,Wigan,169,215,147,267,1986,1602,1024,841,1804,1886,870,638,229,289,9,18,331,316,482,-166,189,142,304,48,45,59,37,31,84,85,76,143
12,Charlton,179,178,122,208,1436,1087,772,552,1639,1644,731,619,158,180,13,8,325,301,386,-85,195,130,266,54,33,46,31,37,65,85,70,111
10,Burnley,161,195,139,260,1721,1421,600,504,1576,1589,732,601,236,273,0,9,325,300,455,-155,194,131,304,52,38,62,31,38,83,83,76,145
37,Swansea,179,170,127,213,1647,1317,678,521,1280,1357,724,557,188,182,6,8,312,306,383,-77,190,122,266,51,37,45,31,29,73,82,66,118
22,Leeds,164,158,155,191,1548,1179,665,542,1594,1574,718,546,206,241,6,13,311,319,349,-30,162,149,228,44,30,40,43,20,51,87,50,91
30,Portsmouth,184,159,108,221,1826,1230,988,628,1691,1756,839,560,194,217,12,8,302,292,380,-88,196,106,266,54,34,45,25,31,77,79,65,122
2,Birmingham,162,140,111,220,1365,1064,707,549,1634,1687,748,565,191,241,13,14,301,273,360,-87,196,105,266,50,46,37,23,36,74,73,82,111
39,Watford,156,205,119,236,1594,1308,529,453,1666,1671,643,588,261,216,13,11,261,275,441,-166,156,105,266,40,36,57,27,24,82,67,60,139
29,Norwich,156,210,95,279,1606,1267,663,489,1403,1455,689,550,189,209,7,9,234,251,489,-238,158,76,266,41,35,57,15,31,87,56,66,144
6,Bournemouth,136,148,105,182,1191,1021,399,347,872,903,540,475,152,139,5,4,211,241,330,-89,127,84,190,34,25,36,22,18,55,56,43,91
9,Brighton,104,125,86,133,1228,958,339,324,1041,1040,525,393,158,128,5,11,209,190,258,-68,117,92,190,27,36,32,21,29,45,48,65,77
20,Hull,107,145,74,178,1106,896,438,343,1180,1148,459,388,143,187,12,12,171,181,323,-142,111,60,190,29,24,42,12,24,59,41,48,101
32,Reading,71,78,65,108,570,503,297,243,583,634,382,325,65,81,5,4,119,136,186,-50,81,38,114,23,12,22,9,11,37,32,23,59
33,Sheffield United,60,63,31,94,620,461,251,165,646,678,345,218,93,109,2,5,115,91,157,-66,76,39,114,22,10,25,9,12,36,31,22,61
21,Ipswich,51,39,47,67,528,365,261,154,382,478,268,162,25,47,1,2,102,98,106,-8,60,42,76,17,9,12,12,6,20,29,15,32
31,QPR,60,77,55,122,843,649,356,304,602,618,285,259,87,104,9,6,92,115,199,-84,63,29,114,15,18,24,7,8,42,22,26,66
16,Derby,55,93,35,118,536,398,257,205,769,788,268,209,97,114,2,4,83,90,211,-121,58,25,114,14,16,27,5,10,42,19,26,69
11,Cardiff,41,73,25,70,458,378,142,110,362,364,205,159,58,56,0,2,64,66,143,-77,40,24,76,11,7,20,6,6,26,17,13,46
19,Huddersfield,26,56,24,78,410,350,112,117,394,422,187,140,53,63,5,2,53,50,134,-84,32,21,76,8,8,22,4,9,25,12,17,47
8,Brentford,22,21,26,35,233,209,77,77,187,184,88,71,29,32,2,1,46,48,56,-8,24,22,38,7,3,9,6,4,9,13,7,18
4,Blackpool,30,37,25,41,253,193,134,101,216,187,94,92,22,25,0,2,39,55,78,-23,20,19,38,5,5,9,5,4,10,10,9,19
14,Coventry,14,23,22,40,213,176,95,82,247,282,127,79,25,51,3,1,34,36,63,-27,19,15,38,4,7,8,4,3,12,8,10,20
7,Bradford,20,29,10,41,221,150,101,73,255,262,108,71,27,30,0,1,26,30,70,-40,19,7,38,4,7,8,1,4,14,5,11,22

In [57]:
# ordering the columns i want to show from this big df
discols =['Team','HGS','HGC','AGS','AGC','TGS','TGC','GD','totalpoints','homepoints','awaypoints','gamesplayed','homewin','homedraw','homeloss','awaywin','awaydraw','awayloss','winsagg','drawsagg','lossagg']

In [58]:
# sorting the big df by points
distable = y20[discols].sort_values(["totalpoints"],axis=0,ascending=False)

In [59]:
distable

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
26,Man United,874,328,688,454,1562,782,780,1698,941,757,836,289,74,55,218,103,97,507,177,152
13,Chelsea,872,338,666,419,1538,757,781,1665,918,747,836,274,96,48,218,93,107,492,189,155
0,Arsenal,892,367,669,509,1561,876,685,1603,929,674,836,281,86,51,189,107,122,470,193,173
24,Liverpool,846,319,670,489,1516,808,708,1591,904,687,836,267,103,48,197,96,125,464,199,173
25,Man City,845,364,633,482,1478,846,632,1440,821,619,798,252,65,82,176,91,132,428,156,214
38,Tottenham,758,425,565,586,1323,1011,312,1370,822,548,836,245,87,86,148,104,166,393,191,252
17,Everton,656,459,446,600,1102,1059,43,1191,725,466,836,207,104,107,114,124,180,321,228,287
28,Newcastle,552,463,391,637,943,1100,-157,973,608,365,760,170,98,112,90,95,195,260,193,307
41,West Ham,520,472,388,588,908,1060,-152,895,538,357,722,150,88,123,88,93,180,238,181,303
1,Aston Villa,457,427,409,582,866,1009,-143,885,504,381,722,132,108,121,93,102,166,225,210,287
34,Southampton,399,350,299,453,698,803,-105,704,417,287,570,111,84,90,70,77,138,181,161,228
18,Fulham,380,363,251,468,631,831,-200,640,423,217,570,120,63,102,42,91,152,162,154,254
23,Leicester,308,262,275,330,583,592,-9,554,324,230,418,90,54,65,60,50,99,150,104,164
3,Blackburn,289,239,229,353,518,592,-74,530,317,213,418,86,59,64,54,51,104,140,110,168
36,Sunderland,288,336,232,459,520,795,-275,520,318,202,532,81,75,110,46,64,156,127,139,266
5,Bolton,278,260,217,353,495,613,-118,506,306,200,418,81,63,65,51,47,111,132,110,176
40,West Brom,295,361,215,411,510,772,-262,490,294,196,494,76,66,105,41,73,133,117,139,238
35,Stoke,248,213,150,312,398,525,-127,457,297,160,380,81,54,55,35,55,100,116,109,155
15,Crystal Palace,213,236,215,309,428,545,-117,437,233,204,380,63,44,83,52,48,90,115,92,173
27,Middlesbrough,251,232,163,271,414,503,-89,432,270,162,380,71,57,62,36,54,100,107,111,162
43,Wolves,181,220,147,242,328,462,-134,348,201,147,304,55,36,61,35,42,75,90,78,136
42,Wigan,169,215,147,267,316,482,-166,331,189,142,304,48,45,59,37,31,84,85,76,143
12,Charlton,179,178,122,208,301,386,-85,325,195,130,266,54,33,46,31,37,65,85,70,111
10,Burnley,161,195,139,260,300,455,-155,325,194,131,304,52,38,62,31,38,83,83,76,145
37,Swansea,179,170,127,213,306,383,-77,312,190,122,266,51,37,45,31,29,73,82,66,118
22,Leeds,164,158,155,191,319,349,-30,311,162,149,228,44,30,40,43,20,51,87,50,91
30,Portsmouth,184,159,108,221,292,380,-88,302,196,106,266,54,34,45,25,31,77,79,65,122
2,Birmingham,162,140,111,220,273,360,-87,301,196,105,266,50,46,37,23,36,74,73,82,111
39,Watford,156,205,119,236,275,441,-166,261,156,105,266,40,36,57,27,24,82,67,60,139
29,Norwich,156,210,95,279,251,489,-238,234,158,76,266,41,35,57,15,31,87,56,66,144
6,Bournemouth,136,148,105,182,241,330,-89,211,127,84,190,34,25,36,22,18,55,56,43,91
9,Brighton,104,125,86,133,190,258,-68,209,117,92,190,27,36,32,21,29,45,48,65,77
20,Hull,107,145,74,178,181,323,-142,171,111,60,190,29,24,42,12,24,59,41,48,101
32,Reading,71,78,65,108,136,186,-50,119,81,38,114,23,12,22,9,11,37,32,23,59
33,Sheffield United,60,63,31,94,91,157,-66,115,76,39,114,22,10,25,9,12,36,31,22,61
21,Ipswich,51,39,47,67,98,106,-8,102,60,42,76,17,9,12,12,6,20,29,15,32
31,QPR,60,77,55,122,115,199,-84,92,63,29,114,15,18,24,7,8,42,22,26,66
16,Derby,55,93,35,118,90,211,-121,83,58,25,114,14,16,27,5,10,42,19,26,69
11,Cardiff,41,73,25,70,66,143,-77,64,40,24,76,11,7,20,6,6,26,17,13,46
19,Huddersfield,26,56,24,78,50,134,-84,53,32,21,76,8,8,22,4,9,25,12,17,47
8,Brentford,22,21,26,35,48,56,-8,46,24,22,38,7,3,9,6,4,9,13,7,18
4,Blackpool,30,37,25,41,55,78,-23,39,20,19,38,5,5,9,5,4,10,10,9,19
14,Coventry,14,23,22,40,36,63,-27,34,19,15,38,4,7,8,4,3,12,8,10,20
7,Bradford,20,29,10,41,30,70,-40,26,19,7,38,4,7,8,1,4,14,5,11,22

# Top 6 vs the rest?

In [60]:
# distable.loc[[26,13,0,24,25,39]]

In [61]:
# distable.loc[[17,29,42,1,35,18,23,3,37,5,41,36,15,28,44,43,12,10,38,22,31,2,40,30,6,9,20,33,34,21,32,16,11,19,27,8,4,14,7]]

In [62]:
# df.loc[df['col1'].isin([value1, value2, value3, ...])]

In [63]:
# distable['winsagg'] = distable['homewin']+distable['awaywin']
# distable['drawsagg'] = distable['homedraw']+distable['awaydraw']
# distable['lossagg'] = distable['homeloss']+distable['awayloss']
# inbigfunc

In [64]:
# distable.head()

In [65]:
# ratios? wins/total*100 = %

In [66]:
distable['win%'] = round((distable['winsagg']/distable['gamesplayed']*100),1)
distable['draw%'] = round((distable['drawsagg']/distable['gamesplayed']*100),1)
distable['loss%'] = round((distable['lossagg']/distable['gamesplayed']*100),1)
# inbigfunc doesnt work in big func have to do after the groupby/sums

In [67]:
distable.head()

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
26,Man United,874,328,688,454,1562,782,780,1698,941,757,836,289,74,55,218,103,97,507,177,152,60.6,21.2,18.2
13,Chelsea,872,338,666,419,1538,757,781,1665,918,747,836,274,96,48,218,93,107,492,189,155,58.9,22.6,18.5
0,Arsenal,892,367,669,509,1561,876,685,1603,929,674,836,281,86,51,189,107,122,470,193,173,56.2,23.1,20.7
24,Liverpool,846,319,670,489,1516,808,708,1591,904,687,836,267,103,48,197,96,125,464,199,173,55.5,23.8,20.7
25,Man City,845,364,633,482,1478,846,632,1440,821,619,798,252,65,82,176,91,132,428,156,214,53.6,19.5,26.8

In [68]:
top6 = distable.loc[distable['Team'].isin(['Man United', 'Chelsea', 'Arsenal', 'Man City', 'Liverpool', 'Tottenham'])]

In [69]:
nottop6 = distable.loc[distable['Team'].isin(['Man United', 'Chelsea', 'Arsenal', 'Man City', 'Liverpool', 'Tottenham'])==False]

In [70]:
top6

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
26,Man United,874,328,688,454,1562,782,780,1698,941,757,836,289,74,55,218,103,97,507,177,152,60.6,21.2,18.2
13,Chelsea,872,338,666,419,1538,757,781,1665,918,747,836,274,96,48,218,93,107,492,189,155,58.9,22.6,18.5
0,Arsenal,892,367,669,509,1561,876,685,1603,929,674,836,281,86,51,189,107,122,470,193,173,56.2,23.1,20.7
24,Liverpool,846,319,670,489,1516,808,708,1591,904,687,836,267,103,48,197,96,125,464,199,173,55.5,23.8,20.7
25,Man City,845,364,633,482,1478,846,632,1440,821,619,798,252,65,82,176,91,132,428,156,214,53.6,19.5,26.8
38,Tottenham,758,425,565,586,1323,1011,312,1370,822,548,836,245,87,86,148,104,166,393,191,252,47.0,22.8,30.1

In [71]:
nottop6

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
17,Everton,656,459,446,600,1102,1059,43,1191,725,466,836,207,104,107,114,124,180,321,228,287,38.4,27.3,34.3
28,Newcastle,552,463,391,637,943,1100,-157,973,608,365,760,170,98,112,90,95,195,260,193,307,34.2,25.4,40.4
41,West Ham,520,472,388,588,908,1060,-152,895,538,357,722,150,88,123,88,93,180,238,181,303,33.0,25.1,42.0
1,Aston Villa,457,427,409,582,866,1009,-143,885,504,381,722,132,108,121,93,102,166,225,210,287,31.2,29.1,39.8
34,Southampton,399,350,299,453,698,803,-105,704,417,287,570,111,84,90,70,77,138,181,161,228,31.8,28.2,40.0
18,Fulham,380,363,251,468,631,831,-200,640,423,217,570,120,63,102,42,91,152,162,154,254,28.4,27.0,44.6
23,Leicester,308,262,275,330,583,592,-9,554,324,230,418,90,54,65,60,50,99,150,104,164,35.9,24.9,39.2
3,Blackburn,289,239,229,353,518,592,-74,530,317,213,418,86,59,64,54,51,104,140,110,168,33.5,26.3,40.2
36,Sunderland,288,336,232,459,520,795,-275,520,318,202,532,81,75,110,46,64,156,127,139,266,23.9,26.1,50.0
5,Bolton,278,260,217,353,495,613,-118,506,306,200,418,81,63,65,51,47,111,132,110,176,31.6,26.3,42.1
40,West Brom,295,361,215,411,510,772,-262,490,294,196,494,76,66,105,41,73,133,117,139,238,23.7,28.1,48.2
35,Stoke,248,213,150,312,398,525,-127,457,297,160,380,81,54,55,35,55,100,116,109,155,30.5,28.7,40.8
15,Crystal Palace,213,236,215,309,428,545,-117,437,233,204,380,63,44,83,52,48,90,115,92,173,30.3,24.2,45.5
27,Middlesbrough,251,232,163,271,414,503,-89,432,270,162,380,71,57,62,36,54,100,107,111,162,28.2,29.2,42.6
43,Wolves,181,220,147,242,328,462,-134,348,201,147,304,55,36,61,35,42,75,90,78,136,29.6,25.7,44.7
42,Wigan,169,215,147,267,316,482,-166,331,189,142,304,48,45,59,37,31,84,85,76,143,28.0,25.0,47.0
12,Charlton,179,178,122,208,301,386,-85,325,195,130,266,54,33,46,31,37,65,85,70,111,32.0,26.3,41.7
10,Burnley,161,195,139,260,300,455,-155,325,194,131,304,52,38,62,31,38,83,83,76,145,27.3,25.0,47.7
37,Swansea,179,170,127,213,306,383,-77,312,190,122,266,51,37,45,31,29,73,82,66,118,30.8,24.8,44.4
22,Leeds,164,158,155,191,319,349,-30,311,162,149,228,44,30,40,43,20,51,87,50,91,38.2,21.9,39.9
30,Portsmouth,184,159,108,221,292,380,-88,302,196,106,266,54,34,45,25,31,77,79,65,122,29.7,24.4,45.9
2,Birmingham,162,140,111,220,273,360,-87,301,196,105,266,50,46,37,23,36,74,73,82,111,27.4,30.8,41.7
39,Watford,156,205,119,236,275,441,-166,261,156,105,266,40,36,57,27,24,82,67,60,139,25.2,22.6,52.3
29,Norwich,156,210,95,279,251,489,-238,234,158,76,266,41,35,57,15,31,87,56,66,144,21.1,24.8,54.1
6,Bournemouth,136,148,105,182,241,330,-89,211,127,84,190,34,25,36,22,18,55,56,43,91,29.5,22.6,47.9
9,Brighton,104,125,86,133,190,258,-68,209,117,92,190,27,36,32,21,29,45,48,65,77,25.3,34.2,40.5
20,Hull,107,145,74,178,181,323,-142,171,111,60,190,29,24,42,12,24,59,41,48,101,21.6,25.3,53.2
32,Reading,71,78,65,108,136,186,-50,119,81,38,114,23,12,22,9,11,37,32,23,59,28.1,20.2,51.8
33,Sheffield United,60,63,31,94,91,157,-66,115,76,39,114,22,10,25,9,12,36,31,22,61,27.2,19.3,53.5
21,Ipswich,51,39,47,67,98,106,-8,102,60,42,76,17,9,12,12,6,20,29,15,32,38.2,19.7,42.1
31,QPR,60,77,55,122,115,199,-84,92,63,29,114,15,18,24,7,8,42,22,26,66,19.3,22.8,57.9
16,Derby,55,93,35,118,90,211,-121,83,58,25,114,14,16,27,5,10,42,19,26,69,16.7,22.8,60.5
11,Cardiff,41,73,25,70,66,143,-77,64,40,24,76,11,7,20,6,6,26,17,13,46,22.4,17.1,60.5
19,Huddersfield,26,56,24,78,50,134,-84,53,32,21,76,8,8,22,4,9,25,12,17,47,15.8,22.4,61.8
8,Brentford,22,21,26,35,48,56,-8,46,24,22,38,7,3,9,6,4,9,13,7,18,34.2,18.4,47.4
4,Blackpool,30,37,25,41,55,78,-23,39,20,19,38,5,5,9,5,4,10,10,9,19,26.3,23.7,50.0
14,Coventry,14,23,22,40,36,63,-27,34,19,15,38,4,7,8,4,3,12,8,10,20,21.1,26.3,52.6
7,Bradford,20,29,10,41,30,70,-40,26,19,7,38,4,7,8,1,4,14,5,11,22,13.2,28.9,57.9

# Win % per season

In [72]:
# shit idea didnt work 
# showed what was expected in almost all cases

# Stats for presenting

In [73]:
distable

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
26,Man United,874,328,688,454,1562,782,780,1698,941,757,836,289,74,55,218,103,97,507,177,152,60.6,21.2,18.2
13,Chelsea,872,338,666,419,1538,757,781,1665,918,747,836,274,96,48,218,93,107,492,189,155,58.9,22.6,18.5
0,Arsenal,892,367,669,509,1561,876,685,1603,929,674,836,281,86,51,189,107,122,470,193,173,56.2,23.1,20.7
24,Liverpool,846,319,670,489,1516,808,708,1591,904,687,836,267,103,48,197,96,125,464,199,173,55.5,23.8,20.7
25,Man City,845,364,633,482,1478,846,632,1440,821,619,798,252,65,82,176,91,132,428,156,214,53.6,19.5,26.8
38,Tottenham,758,425,565,586,1323,1011,312,1370,822,548,836,245,87,86,148,104,166,393,191,252,47.0,22.8,30.1
17,Everton,656,459,446,600,1102,1059,43,1191,725,466,836,207,104,107,114,124,180,321,228,287,38.4,27.3,34.3
28,Newcastle,552,463,391,637,943,1100,-157,973,608,365,760,170,98,112,90,95,195,260,193,307,34.2,25.4,40.4
41,West Ham,520,472,388,588,908,1060,-152,895,538,357,722,150,88,123,88,93,180,238,181,303,33.0,25.1,42.0
1,Aston Villa,457,427,409,582,866,1009,-143,885,504,381,722,132,108,121,93,102,166,225,210,287,31.2,29.1,39.8
34,Southampton,399,350,299,453,698,803,-105,704,417,287,570,111,84,90,70,77,138,181,161,228,31.8,28.2,40.0
18,Fulham,380,363,251,468,631,831,-200,640,423,217,570,120,63,102,42,91,152,162,154,254,28.4,27.0,44.6
23,Leicester,308,262,275,330,583,592,-9,554,324,230,418,90,54,65,60,50,99,150,104,164,35.9,24.9,39.2
3,Blackburn,289,239,229,353,518,592,-74,530,317,213,418,86,59,64,54,51,104,140,110,168,33.5,26.3,40.2
36,Sunderland,288,336,232,459,520,795,-275,520,318,202,532,81,75,110,46,64,156,127,139,266,23.9,26.1,50.0
5,Bolton,278,260,217,353,495,613,-118,506,306,200,418,81,63,65,51,47,111,132,110,176,31.6,26.3,42.1
40,West Brom,295,361,215,411,510,772,-262,490,294,196,494,76,66,105,41,73,133,117,139,238,23.7,28.1,48.2
35,Stoke,248,213,150,312,398,525,-127,457,297,160,380,81,54,55,35,55,100,116,109,155,30.5,28.7,40.8
15,Crystal Palace,213,236,215,309,428,545,-117,437,233,204,380,63,44,83,52,48,90,115,92,173,30.3,24.2,45.5
27,Middlesbrough,251,232,163,271,414,503,-89,432,270,162,380,71,57,62,36,54,100,107,111,162,28.2,29.2,42.6
43,Wolves,181,220,147,242,328,462,-134,348,201,147,304,55,36,61,35,42,75,90,78,136,29.6,25.7,44.7
42,Wigan,169,215,147,267,316,482,-166,331,189,142,304,48,45,59,37,31,84,85,76,143,28.0,25.0,47.0
12,Charlton,179,178,122,208,301,386,-85,325,195,130,266,54,33,46,31,37,65,85,70,111,32.0,26.3,41.7
10,Burnley,161,195,139,260,300,455,-155,325,194,131,304,52,38,62,31,38,83,83,76,145,27.3,25.0,47.7
37,Swansea,179,170,127,213,306,383,-77,312,190,122,266,51,37,45,31,29,73,82,66,118,30.8,24.8,44.4
22,Leeds,164,158,155,191,319,349,-30,311,162,149,228,44,30,40,43,20,51,87,50,91,38.2,21.9,39.9
30,Portsmouth,184,159,108,221,292,380,-88,302,196,106,266,54,34,45,25,31,77,79,65,122,29.7,24.4,45.9
2,Birmingham,162,140,111,220,273,360,-87,301,196,105,266,50,46,37,23,36,74,73,82,111,27.4,30.8,41.7
39,Watford,156,205,119,236,275,441,-166,261,156,105,266,40,36,57,27,24,82,67,60,139,25.2,22.6,52.3
29,Norwich,156,210,95,279,251,489,-238,234,158,76,266,41,35,57,15,31,87,56,66,144,21.1,24.8,54.1
6,Bournemouth,136,148,105,182,241,330,-89,211,127,84,190,34,25,36,22,18,55,56,43,91,29.5,22.6,47.9
9,Brighton,104,125,86,133,190,258,-68,209,117,92,190,27,36,32,21,29,45,48,65,77,25.3,34.2,40.5
20,Hull,107,145,74,178,181,323,-142,171,111,60,190,29,24,42,12,24,59,41,48,101,21.6,25.3,53.2
32,Reading,71,78,65,108,136,186,-50,119,81,38,114,23,12,22,9,11,37,32,23,59,28.1,20.2,51.8
33,Sheffield United,60,63,31,94,91,157,-66,115,76,39,114,22,10,25,9,12,36,31,22,61,27.2,19.3,53.5
21,Ipswich,51,39,47,67,98,106,-8,102,60,42,76,17,9,12,12,6,20,29,15,32,38.2,19.7,42.1
31,QPR,60,77,55,122,115,199,-84,92,63,29,114,15,18,24,7,8,42,22,26,66,19.3,22.8,57.9
16,Derby,55,93,35,118,90,211,-121,83,58,25,114,14,16,27,5,10,42,19,26,69,16.7,22.8,60.5
11,Cardiff,41,73,25,70,66,143,-77,64,40,24,76,11,7,20,6,6,26,17,13,46,22.4,17.1,60.5
19,Huddersfield,26,56,24,78,50,134,-84,53,32,21,76,8,8,22,4,9,25,12,17,47,15.8,22.4,61.8
8,Brentford,22,21,26,35,48,56,-8,46,24,22,38,7,3,9,6,4,9,13,7,18,34.2,18.4,47.4
4,Blackpool,30,37,25,41,55,78,-23,39,20,19,38,5,5,9,5,4,10,10,9,19,26.3,23.7,50.0
14,Coventry,14,23,22,40,36,63,-27,34,19,15,38,4,7,8,4,3,12,8,10,20,21.1,26.3,52.6
7,Bradford,20,29,10,41,30,70,-40,26,19,7,38,4,7,8,1,4,14,5,11,22,13.2,28.9,57.9

In [74]:
winnersdic = {
             'ManUnited':7,
             'ManCity':6,
             'Chelsea':5,
             'Arsenal':2,
             'Leicester':1,
             'Liverpool':1}

In [75]:
winnersdic

{'ManUnited': 7,
 'ManCity': 6,
 'Chelsea': 5,
 'Arsenal': 2,
 'Leicester': 1,
 'Liverpool': 1}

In [76]:
presentings = distable
presentings

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
26,Man United,874,328,688,454,1562,782,780,1698,941,757,836,289,74,55,218,103,97,507,177,152,60.6,21.2,18.2
13,Chelsea,872,338,666,419,1538,757,781,1665,918,747,836,274,96,48,218,93,107,492,189,155,58.9,22.6,18.5
0,Arsenal,892,367,669,509,1561,876,685,1603,929,674,836,281,86,51,189,107,122,470,193,173,56.2,23.1,20.7
24,Liverpool,846,319,670,489,1516,808,708,1591,904,687,836,267,103,48,197,96,125,464,199,173,55.5,23.8,20.7
25,Man City,845,364,633,482,1478,846,632,1440,821,619,798,252,65,82,176,91,132,428,156,214,53.6,19.5,26.8
38,Tottenham,758,425,565,586,1323,1011,312,1370,822,548,836,245,87,86,148,104,166,393,191,252,47.0,22.8,30.1
17,Everton,656,459,446,600,1102,1059,43,1191,725,466,836,207,104,107,114,124,180,321,228,287,38.4,27.3,34.3
28,Newcastle,552,463,391,637,943,1100,-157,973,608,365,760,170,98,112,90,95,195,260,193,307,34.2,25.4,40.4
41,West Ham,520,472,388,588,908,1060,-152,895,538,357,722,150,88,123,88,93,180,238,181,303,33.0,25.1,42.0
1,Aston Villa,457,427,409,582,866,1009,-143,885,504,381,722,132,108,121,93,102,166,225,210,287,31.2,29.1,39.8
34,Southampton,399,350,299,453,698,803,-105,704,417,287,570,111,84,90,70,77,138,181,161,228,31.8,28.2,40.0
18,Fulham,380,363,251,468,631,831,-200,640,423,217,570,120,63,102,42,91,152,162,154,254,28.4,27.0,44.6
23,Leicester,308,262,275,330,583,592,-9,554,324,230,418,90,54,65,60,50,99,150,104,164,35.9,24.9,39.2
3,Blackburn,289,239,229,353,518,592,-74,530,317,213,418,86,59,64,54,51,104,140,110,168,33.5,26.3,40.2
36,Sunderland,288,336,232,459,520,795,-275,520,318,202,532,81,75,110,46,64,156,127,139,266,23.9,26.1,50.0
5,Bolton,278,260,217,353,495,613,-118,506,306,200,418,81,63,65,51,47,111,132,110,176,31.6,26.3,42.1
40,West Brom,295,361,215,411,510,772,-262,490,294,196,494,76,66,105,41,73,133,117,139,238,23.7,28.1,48.2
35,Stoke,248,213,150,312,398,525,-127,457,297,160,380,81,54,55,35,55,100,116,109,155,30.5,28.7,40.8
15,Crystal Palace,213,236,215,309,428,545,-117,437,233,204,380,63,44,83,52,48,90,115,92,173,30.3,24.2,45.5
27,Middlesbrough,251,232,163,271,414,503,-89,432,270,162,380,71,57,62,36,54,100,107,111,162,28.2,29.2,42.6
43,Wolves,181,220,147,242,328,462,-134,348,201,147,304,55,36,61,35,42,75,90,78,136,29.6,25.7,44.7
42,Wigan,169,215,147,267,316,482,-166,331,189,142,304,48,45,59,37,31,84,85,76,143,28.0,25.0,47.0
12,Charlton,179,178,122,208,301,386,-85,325,195,130,266,54,33,46,31,37,65,85,70,111,32.0,26.3,41.7
10,Burnley,161,195,139,260,300,455,-155,325,194,131,304,52,38,62,31,38,83,83,76,145,27.3,25.0,47.7
37,Swansea,179,170,127,213,306,383,-77,312,190,122,266,51,37,45,31,29,73,82,66,118,30.8,24.8,44.4
22,Leeds,164,158,155,191,319,349,-30,311,162,149,228,44,30,40,43,20,51,87,50,91,38.2,21.9,39.9
30,Portsmouth,184,159,108,221,292,380,-88,302,196,106,266,54,34,45,25,31,77,79,65,122,29.7,24.4,45.9
2,Birmingham,162,140,111,220,273,360,-87,301,196,105,266,50,46,37,23,36,74,73,82,111,27.4,30.8,41.7
39,Watford,156,205,119,236,275,441,-166,261,156,105,266,40,36,57,27,24,82,67,60,139,25.2,22.6,52.3
29,Norwich,156,210,95,279,251,489,-238,234,158,76,266,41,35,57,15,31,87,56,66,144,21.1,24.8,54.1
6,Bournemouth,136,148,105,182,241,330,-89,211,127,84,190,34,25,36,22,18,55,56,43,91,29.5,22.6,47.9
9,Brighton,104,125,86,133,190,258,-68,209,117,92,190,27,36,32,21,29,45,48,65,77,25.3,34.2,40.5
20,Hull,107,145,74,178,181,323,-142,171,111,60,190,29,24,42,12,24,59,41,48,101,21.6,25.3,53.2
32,Reading,71,78,65,108,136,186,-50,119,81,38,114,23,12,22,9,11,37,32,23,59,28.1,20.2,51.8
33,Sheffield United,60,63,31,94,91,157,-66,115,76,39,114,22,10,25,9,12,36,31,22,61,27.2,19.3,53.5
21,Ipswich,51,39,47,67,98,106,-8,102,60,42,76,17,9,12,12,6,20,29,15,32,38.2,19.7,42.1
31,QPR,60,77,55,122,115,199,-84,92,63,29,114,15,18,24,7,8,42,22,26,66,19.3,22.8,57.9
16,Derby,55,93,35,118,90,211,-121,83,58,25,114,14,16,27,5,10,42,19,26,69,16.7,22.8,60.5
11,Cardiff,41,73,25,70,66,143,-77,64,40,24,76,11,7,20,6,6,26,17,13,46,22.4,17.1,60.5
19,Huddersfield,26,56,24,78,50,134,-84,53,32,21,76,8,8,22,4,9,25,12,17,47,15.8,22.4,61.8
8,Brentford,22,21,26,35,48,56,-8,46,24,22,38,7,3,9,6,4,9,13,7,18,34.2,18.4,47.4
4,Blackpool,30,37,25,41,55,78,-23,39,20,19,38,5,5,9,5,4,10,10,9,19,26.3,23.7,50.0
14,Coventry,14,23,22,40,36,63,-27,34,19,15,38,4,7,8,4,3,12,8,10,20,21.1,26.3,52.6
7,Bradford,20,29,10,41,30,70,-40,26,19,7,38,4,7,8,1,4,14,5,11,22,13.2,28.9,57.9

In [77]:
presentings['gamesplayed'].sum()

16720

In [78]:
presentings['winsagg'].sum()

6275

In [79]:
presentings['drawsagg'].sum()

4170

In [80]:
presentings['lossagg'].sum()

6275

In [84]:
sr0001 = winpct(sr0001)

In [85]:
sr0001

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
0,Arsenal,45,13,18,25,323,217,189,106,248,247,176,119,17,31,1,2,70,63,38,25,48,22,38,15,3,1,5,7,7,20,10,8,52.6,26.3,21.1
1,Aston Villa,27,20,19,23,183,166,88,77,205,286,111,75,24,42,1,2,54,46,43,3,32,22,38,8,8,3,5,7,7,13,15,10,34.2,39.5,26.3
2,Bradford,20,29,10,41,221,150,101,73,255,262,108,71,27,30,0,1,26,30,70,-40,19,7,38,4,7,8,1,4,14,5,11,22,13.2,28.9,57.9
3,Charlton,31,19,19,38,206,167,119,98,233,234,114,99,24,20,2,1,52,50,57,-7,38,14,38,11,5,3,3,5,11,14,10,14,36.8,26.3,36.8
4,Chelsea,44,20,24,25,280,224,136,104,257,288,118,94,30,45,0,2,61,68,45,23,42,19,38,13,3,3,4,7,8,17,10,11,44.7,26.3,28.9
5,Coventry,14,23,22,40,213,176,95,82,247,282,127,79,25,51,3,1,34,36,63,-27,19,15,38,4,7,8,4,3,12,8,10,20,21.1,26.3,52.6
6,Derby,23,24,14,35,148,157,65,76,270,259,80,79,37,39,1,1,42,37,59,-22,31,11,38,8,7,4,2,5,12,10,12,16,26.3,31.6,42.1
7,Everton,29,27,16,32,229,165,117,78,266,292,110,93,37,37,2,3,42,45,59,-14,26,16,38,6,8,5,5,1,13,11,9,18,28.9,23.7,47.4
8,Ipswich,31,15,26,27,298,193,141,85,199,215,124,82,10,21,1,1,66,57,42,15,38,28,38,11,5,3,9,1,9,20,6,12,52.6,15.8,31.6
9,Leeds,36,21,28,22,281,194,132,96,300,289,169,101,30,42,0,3,68,64,43,21,36,32,38,11,3,5,9,5,5,20,8,10,52.6,21.1,26.3
10,Leicester,28,23,11,28,199,127,97,62,188,238,99,75,24,32,1,1,48,39,51,-12,34,14,38,10,4,5,4,2,13,14,6,18,36.8,15.8,47.4
11,Liverpool,40,14,31,25,282,206,142,107,219,254,145,98,21,29,2,2,69,71,39,32,43,26,38,13,4,2,7,5,7,20,9,9,52.6,23.7,23.7
12,Man City,20,31,21,34,204,173,98,76,284,305,135,85,37,32,1,2,34,41,65,-24,15,19,38,4,3,12,4,7,8,8,10,20,21.1,26.3,52.6
13,Man United,49,12,30,19,323,233,152,112,195,238,151,118,13,31,2,1,80,79,31,48,47,33,38,15,2,2,9,6,4,24,8,6,63.2,21.1,15.8
14,Middlesbrough,18,23,26,21,212,140,93,74,215,283,85,61,28,44,4,2,42,44,44,0,19,23,38,4,7,8,5,8,6,9,15,14,23.7,39.5,36.8
15,Newcastle,26,17,18,33,245,169,104,87,286,266,101,92,18,30,2,3,51,44,50,-6,34,17,38,10,4,5,4,5,10,14,9,15,36.8,23.7,39.5
16,Southampton,27,22,13,26,243,171,100,74,246,263,115,96,24,25,1,0,52,40,48,-8,35,17,38,11,2,6,3,8,8,14,10,14,36.8,26.3,36.8
17,Sunderland,24,16,22,25,256,193,134,84,286,332,102,85,34,39,3,2,57,46,41,5,34,23,38,9,7,3,6,5,8,15,12,11,39.5,31.6,28.9
18,Tottenham,31,16,16,38,235,148,107,74,270,256,105,66,18,27,3,0,49,47,54,-7,39,10,38,11,6,2,2,4,13,13,10,15,34.2,26.3,39.5
19,West Ham,24,20,21,30,280,195,132,97,263,210,115,98,34,35,2,1,42,45,50,-5,24,18,38,6,6,7,4,6,9,10,12,16,26.3,31.6,42.1

In [87]:
s0001 = winpct(sr0001)
s0102 = winpct(sr0102)
s0203 = winpct(sr0203)
s0304 = winpct(sr0304)
s0405 = winpct(sr0405)
s0506 = winpct(sr0506)
s0607 = winpct(sr0607)
s0708 = winpct(sr0708)
s0809 = winpct(sr0809)
s0910 = winpct(sr0910)
s1011 = winpct(sr1011)
s1112 = winpct(sr1112)
s1213 = winpct(sr1213)
s1314 = winpct(sr1314)
s1415 = winpct(sr1415)
s1516 = winpct(sr1516)
s1617 = winpct(sr1617)
s1718 = winpct(sr1718)
s1819 = winpct(sr1819)
s1920 = winpct(sr1920)
s2021 = winpct(sr2021)
s2122 = winpct(sr2122)

In [88]:
winlist = [s0001,
s0102,
s0203,
s0304,
s0405,
s0506,
s0607,
s0708,
s0809,
s0910,
s1011,
s1112,
s1213,
s1314,
s1415,
s1516,
s1617,
s1718,
s1819,
s1920,
s2021,
s2122]

In [89]:
bigtablewp = pd.concat(winlist,axis=0).reset_index(drop=True)

In [90]:
bigtablewp

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
0,Arsenal,45,13,18,25,323,217,189,106,248,247,176,119,17,31,1,2,70,63,38,25,48,22,38,15,3,1,5,7,7,20,10,8,52.6,26.3,21.1
1,Aston Villa,27,20,19,23,183,166,88,77,205,286,111,75,24,42,1,2,54,46,43,3,32,22,38,8,8,3,5,7,7,13,15,10,34.2,39.5,26.3
2,Bradford,20,29,10,41,221,150,101,73,255,262,108,71,27,30,0,1,26,30,70,-40,19,7,38,4,7,8,1,4,14,5,11,22,13.2,28.9,57.9
3,Charlton,31,19,19,38,206,167,119,98,233,234,114,99,24,20,2,1,52,50,57,-7,38,14,38,11,5,3,3,5,11,14,10,14,36.8,26.3,36.8
4,Chelsea,44,20,24,25,280,224,136,104,257,288,118,94,30,45,0,2,61,68,45,23,42,19,38,13,3,3,4,7,8,17,10,11,44.7,26.3,28.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,Southampton,23,24,20,43,236,246,87,83,206,196,115,119,31,32,1,1,40,43,67,-24,25,15,38,6,7,6,3,6,10,9,13,16,23.7,34.2,42.1
436,Tottenham,38,19,31,21,260,231,97,101,208,178,106,89,34,33,0,1,71,69,40,29,40,31,38,13,1,5,9,4,6,22,5,11,57.9,13.2,28.9
437,Watford,17,46,17,31,216,180,69,58,215,225,84,78,33,24,1,2,23,34,77,-43,8,15,38,2,2,15,4,3,12,6,5,27,15.8,13.2,71.1
438,West Ham,33,26,27,25,232,201,85,73,162,162,106,85,27,20,0,3,56,60,51,9,32,24,38,9,5,5,7,3,9,16,8,14,42.1,21.1,36.8
439,Wolves,20,25,18,18,223,179,71,65,177,188,88,80,31,28,1,1,51,38,43,-5,24,27,38,7,3,9,8,3,8,15,6,17,39.5,15.8,44.7

In [ ]:
# distable = y20[discols].sort_values(["totalpoints"],axis=0,ascending=False)

In [91]:
bigtablewp.sort_values(["win%"],axis=0,ascending=False)

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg,win%,draw%,loss%
372,Man City,57,12,38,11,386,297,148,112,162,166,143,144,17,27,0,1,98,95,23,72,54,44,38,18,0,1,14,2,3,32,2,4,84.2,5.3,10.5
350,Man City,61,14,45,13,347,317,151,110,169,175,138,146,26,32,1,1,100,106,27,79,50,50,38,16,2,1,16,2,1,32,4,2,84.2,10.5,5.3
389,Liverpool,52,16,33,17,314,276,129,102,156,175,144,114,13,25,1,0,99,85,33,52,55,44,38,18,1,0,14,2,3,32,3,3,84.2,7.9,7.9
323,Chelsea,55,17,30,16,316,264,121,83,185,209,129,89,32,40,0,0,93,85,33,52,51,42,38,17,0,2,13,3,3,30,3,5,78.9,7.9,13.2
371,Liverpool,55,10,34,12,335,239,126,100,149,166,133,116,13,24,1,1,97,89,22,67,53,44,38,17,2,0,13,5,1,30,7,1,78.9,18.4,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,QPR,13,28,17,32,265,200,133,112,177,207,89,81,22,37,2,1,25,30,60,-30,14,11,38,2,8,9,2,5,12,4,13,21,10.5,34.2,55.3
115,Sunderland,12,37,14,32,192,145,111,72,257,281,103,74,28,41,0,4,15,26,69,-43,7,8,38,1,4,14,2,2,15,3,6,29,7.9,15.8,76.3
369,Huddersfield,10,31,12,45,203,197,57,61,214,206,85,77,27,28,3,1,16,22,76,-54,9,7,38,2,3,14,1,4,14,3,7,28,7.9,18.4,73.7
301,Aston Villa,14,35,13,41,206,162,62,49,194,237,94,73,35,40,1,2,17,27,76,-49,11,6,38,2,5,12,1,3,15,3,8,27,7.9,21.1,71.1
146,Derby,12,43,8,46,193,142,105,77,238,266,82,74,27,35,1,0,11,20,89,-69,8,3,38,1,5,13,0,3,16,1,8,29,2.6,21.1,76.3

In [95]:
winpttable = bigtablewp[['Team','totalpoints','TGC','TGC','GD','win%','draw%','loss%','homepoints','awaypoints','gamesplayed','homewin','homedraw','homeloss','awaywin','awayloss','winsagg','drawsagg','lossagg']].sort_values(["win%"],axis=0,ascending=False)

In [96]:
winpttable

,Team,totalpoints,TGC,TGC,GD,win%,draw%,loss%,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awayloss,winsagg,drawsagg,lossagg
372,Man City,98,23,23,72,84.2,5.3,10.5,54,44,38,18,0,1,14,3,32,2,4
350,Man City,100,27,27,79,84.2,10.5,5.3,50,50,38,16,2,1,16,1,32,4,2
389,Liverpool,99,33,33,52,84.2,7.9,7.9,55,44,38,18,1,0,14,3,32,3,3
323,Chelsea,93,33,33,52,78.9,7.9,13.2,51,42,38,17,0,2,13,3,30,3,5
371,Liverpool,97,22,22,67,78.9,18.4,2.6,53,44,38,17,2,0,13,1,30,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,QPR,25,60,60,-30,10.5,34.2,55.3,14,11,38,2,8,9,2,12,4,13,21
115,Sunderland,15,69,69,-43,7.9,15.8,76.3,7,8,38,1,4,14,2,15,3,6,29
369,Huddersfield,16,76,76,-54,7.9,18.4,73.7,9,7,38,2,3,14,1,14,3,7,28
301,Aston Villa,17,76,76,-49,7.9,21.1,71.1,11,6,38,2,5,12,1,15,3,8,27
146,Derby,11,89,89,-69,2.6,21.1,76.3,8,3,38,1,5,13,0,16,1,8,29

In [ ]:
# predicting home wins vs non home wins
# stat analysis into this? make some graphs?
# nfc

In [81]:
def winpct(df):
    
    df['win%'] = round((df['winsagg']/df['gamesplayed']*100),1)
    df['draw%'] = round((df['drawsagg']/df['gamesplayed']*100),1)
    df['loss%'] = round((df['lossagg']/df['gamesplayed']*100),1)

    return(df)

In [82]:
y20list

[             Team  HGS  HGC  AGS  AGC   HS   AS  HST  AST   HF   AF   HC   AC  \
 0         Arsenal   45   13   18   25  323  217  189  106  248  247  176  119
 1     Aston Villa   27   20   19   23  183  166   88   77  205  286  111   75
 2        Bradford   20   29   10   41  221  150  101   73  255  262  108   71
 3        Charlton   31   19   19   38  206  167  119   98  233  234  114   99
 4         Chelsea   44   20   24   25  280  224  136  104  257  288  118   94
 5        Coventry   14   23   22   40  213  176   95   82  247  282  127   79
 6           Derby   23   24   14   35  148  157   65   76  270  259   80   79
 7         Everton   29   27   16   32  229  165  117   78  266  292  110   93
 8         Ipswich   31   15   26   27  298  193  141   85  199  215  124   82
 9           Leeds   36   21   28   22  281  194  132   96  300  289  169  101
 10      Leicester   28   23   11   28  199  127   97   62  188  238   99   75
 11      Liverpool   40   14   31   25  282  206  142  107  219  254  145   98
 12       Man City   20   31   21   34  204  173   98   76  284  305  135   85
 13     Man United   49   12   30   19  323  233  152  112  195  238  151  118
 14  Middlesbrough   18   23   26   21  212  140   93   74  215  283   85   61
 15      Newcastle   26   17   18   33  245  169  104   87  286  266  101   92
 16    Southampton   27   22   13   26  243  171  100   74  246  263  115   96
 17     Sunderland   24   16   22   25  256  193  134   84  286  332  102   85
 18      Tottenham   31   16   16   38  235  148  107   74  270  256  105   66
 19       West Ham   24   20   21   30  280  195  132   97  263  210  115   98

     HY  AY  HR  AR  totalpoints  TGS  TGC  GD  homepoints  awaypoints  \
 0   17  31   1   2           70   63   38  25          48          22
 1   24  42   1   2           54   46   43   3          32          22
 2   27  30   0   1           26   30   70 -40          19           7
 3   24  20   2   1           52   50   57  -7          38          14
 4   30  45   0   2           61   68   45  23          42          19
 5   25  51   3   1           34   36   63 -27          19          15
 6   37  39   1   1           42   37   59 -22          31          11
 7   37  37   2   3           42   45   59 -14          26          16
 8   10  21   1   1           66   57   42  15          38          28
 9   30  42   0   3           68   64   43  21          36          32
 10  24  32   1   1           48   39   51 -12          34          14
 11  21  29   2   2           69   71   39  32          43          26
 12  37  32   1   2           34   41   65 -24          15          19
 13  13  31   2   1           80   79   31  48          47          33
 14  28  44   4   2           42   44   44   0          19          23
 15  18  30   2   3           51   44   50  -6          34          17
 16  24  25   1   0           52   40   48  -8          35          17
 17  34  39   3   2           57   46   41   5          34          23
 18  18  27   3   0           49   47   54  -7          39          10
 19  34  35   2   1           42   45   50  -5          24          18

     gamesplayed  homewin  homedraw  homeloss  awaywin  awaydraw  awayloss  \
 0            38       15         3         1        5         7         7
 1            38        8         8         3        5         7         7
 2            38        4         7         8        1         4        14
 3            38       11         5         3        3         5        11
 4            38       13         3         3        4         7         8
 5            38        4         7         8        4         3        12
 6            38        8         7         4        2         5        12
 7            38        6         8         5        5         1        13
 8            38       11         5         3        9         1         9
 9            38       11         3         5        9         5         5
 10           38       10         4         5        4         2        13
 11           38       13         4         2        7         5         7
 12           38        4         3        12        4         7         8
 13           38       15         2         2        9         6         4
 14           38        4         7         8        5         8         6
 15           38       10         4         5        4         5        10
 16           38       11         2         6        3         8         8
 17           38        9         7         3        6         5         8
 18           38       11         6         2        2         4        13
 19           38        6         6         7        4         6         9

     winsagg  drawsagg  lossagg
 0        20        10        8
 1        13        15       10
 2         5        11       22
 3        14        10       14
 4        17        10       11
 5         8        10       20
 6        10        12       16
 7        11         9       18
 8        20         6       12
 9        20         8       10
 10       14         6       18
 11       20         9        9
 12        8        10       20
 13       24         8        6
 14        9        15       14
 15       14         9       15
 16       14        10       14
 17       15        12       11
 18       13        10       15
 19       10        12       16  ,
              Team  HGS  HGC  AGS  AGC   HS   AS  HST  AST   HF   AF   HC   AC  \
 0         Arsenal   42   25   37   11  317  201  154  107  259  302  150   96
 1     Aston Villa   22   17   24   30  186  196   91   98  228  264  119   82
 2       Blackburn   33   20   22   31  260  182  126   87  270  296  117  119
 3          Bolton   20   31   24   31  199  167   79   81  240  271  114   80
 4        Charlton   23   30   15   19  195  176  100   78  246  235  141  101
 5         Chelsea   43   21   23   17  287  199  134   81  235  261  119  100
 6           Derby   20   26   13   37  195   99   87   52  261  263  106   56
 7         Everton   26   23   19   34  223  161  114   81  267  273  110   73
 8          Fulham   21   16   15   28  209  170   89   68  242  249  113   98
 9         Ipswich   20   24   21   40  230  172  120   69  183  263  144   80
 10          Leeds   31   21   22   16  279  191  133  102  274  320  122   92
 11      Leicester   15   34   15   30  179  125   91   67  273  262  115   82
 12      Liverpool   33   14   34   16  235  191  105  109  206  224  105   83
 13     Man United   40   17   47   28  285  254  126  130  221  215  154  110
 14  Middlesbrough   23   26   12   21  173  139   75   55  248  257  101   67
 15      Newcastle   40   23   34   29  263  201  129   94  243  255  155  107
 16    Southampton   23   22   23   32  188  169   86   81  267  274   99   76
 17     Sunderland   18   16   11   35  264  170  134   68  270  280  110   86
 18      Tottenham   32   24   17   29  232  180  102   76  232  225  119   87
 19       West Ham   32   14   16   43  257  162  127   71  226  232  128   82

     HY  AY  HR  AR  totalpoints  TGS  TGC  GD  homepoints  awaypoints  \
 0   32  45   2   4           87   79   36  43          40          47
 1   16  25   1   1           50   46   47  -1          31          19
 2   27  31   2   2           46   55   51   4          30          16
 3   22  35   5   2           40   44   62 -18          22          18
 4   27  35   2   1           44   38   49 -11          21          23
 5   30  40   1   2           64   66   38  28          37          27
 6   33  40   0   3           30   33   63 -30          19          11
 7   18  37   2   1           43   45   57 -12          28          15
 8   27  28   2   0           44   36   44  -8          28          16
 9   15  26   0   1           36   41   64 -23          22          14
 10  28  44   1   4           66   53   37  16          33          33
 11  30  46   2   3           28   30   64 -34          16          12
 12  14  27   2   1           80   67   30  37          41          39
 13  30  24   0   1           77   87   45  42          35          42
 14  21  30   4   3           45   35   47 -12          26          19
 15  17  33   0   2           71   74   52  22          39          32
 16  15  24   4   2           45   46   54  -8          26          19
 17  29  39   1   0           40   29   51 -22          28          12
 18  18  40   1   4           50   49   53  -4          34          16
 19  30  37   0   3           53   48   57  -9          40          13

     gamesplayed  homewin  homedraw  homeloss  awaywin  awaydraw  awayloss  \
 0            38       12         4         3       14         5         0
 1            38        8         7         4        4         7         8
 2            38        8         6         5        4         4        11
 3            38        5         7         7        4         6         9
 4            38        5         6         8        5         8         6
 5            38       11         4         4        6         9         4
 6            38        5         4        10        3         2        14
 7            38        8         4         7        3         6        10
 8            38        7         7         5        3         7         9
 9            38        6         4         9        3         5        11
 10           38        9         6         4        9         6         4
 11           38        3         7         9        2         6        11
 12           38       12         5         2       12         3         4
 13           38       11         2         6       13         3         3
 14           38        7         5         7        5         4        10
 15           38       12         3         4        9         5         5
 16           38        7         5         7        5         4        10
 17           38        7         7         5        3         3        13
 18           38       10         4         5        4         4        11
 19           38       12         4         3        3         4        12

     winsagg  drawsagg  lossagg
 0        26         9        3
 1        12        14       12
 2        12        10       16
 3         9        13       16
 4        10        14       14
 5        17        13        8
 6         8         6       24
 7        11        10       17
 8        10        14       14
 9         9         9       20
 10       18        12        8
 11        5        13       20
 12       24         8        6
 13       24         5        9
 14       12         9       17
 15       21         8        9
 16       12         9       17
 17       10        10       18
 18       14         8       16
 19       15         8       15  ,
              Team  HGS  HGC  AGS  AGC   HS   AS  HST  AST   HF   AF   HC   AC  \
 0         Arsenal   47   20   38   22  299  199  176  120  232  251  156  110
 1     Aston Villa   25   14   17   33  263  219  130  103  243  271  132  108
 2      Birmingham   25   23   16   26  185  154  101   68  275  227   98   85
 3       Blackburn   24   15   28   28  242  187  122   99  264  265  127   87
 4          Bolton   27   24   14   27  265  158  138   73  217  204  119   77
 5        Charlton   26   30   19   26  210  148  121   84  235  258   99  102
 6         Chelsea   41   15   27   23  249  224  133  125  200  245  112  102
 7         Everton   28   19   20   30  244  193  135  104  254  277  154  106
 8          Fulham   26   18   15   32  205  159  101   81  225  261  111   92
 9           Leeds   25   26   33   31  249  164  111   99  279  268  107   72
 10      Liverpool   30   16   31   25  298  207  173  111  189  215  132   94
 11       Man City   28   26   19   28  261  180  150   93  204  241  148   94
 12     Man United   42   12   32   22  309  222  180  128  209  223  160  108
 13  Middlesbrough   36   21   12   23  234  155  107   77  241  235  114   97
 14      Newcastle   36   17   27   31  274  215  170  114  200  243  147  113
 15    Southampton   25   16   18   30  248  212  128   99  253  254  119   98
 16     Sunderland   11   31   10   34  200  124   95   68  287  243  130   86
 17      Tottenham   30   29   21   33  238  158  125   89  271  217  125   98
 18      West Brom   17   34   12   31  195  180   98   89  247  263   98   76
 19       West Ham   21   24   21   35  208  186  111   82  266  214  128   82

     HY  AY  HR  AR  totalpoints  TGS  TGC  GD  homepoints  awaypoints  \
 0   22  33   1   2           78   85   42  43          47          31
 1   30  34   4   0           45   42   47  -5          35          10
 2   30  41   1   4           48   41   49  -8          29          19
 3   28  34   1   3           60   52   43   9          34          26
 4   29  39   2   2           44   41   51 -10          29          15
 5   24  30   2   0           49   45   56 -11          27          22
 6   32  31   0   1           67   68   38  30          41          26
 7   29  24   4   3           59   48   49  -1          38          21
 8   20  36   2   4           48   41   50  -9          36          12
 9   28  43   0   2           47   58   57   1          24          23
 10  15  29   0   3           64   61   41  20          35          29
 11  19  35   3   3           51   47   54  -7          29          22
 12  16  29   0   1           83   74   34  40          50          33
 13  21  29   1   4           49   48   44   4          37          12
 14  19  29   1   2           69   63   48  15          47          22
 15  23  24   1   2           52   43   46  -3          35          17
 16  27  33   0   1           19   21   65 -44          11           8
 17  29  31   3   3           50   51   62 -11          31          19
 18  26  27   0   4           26   29   65 -36          14          12
 19  33  31   1   4           42   42   59 -17          22          20

     gamesplayed  homewin  homedraw  homeloss  awaywin  awaydraw  awayloss  \
 0            38       15         2         2        8         7         4
 1            38       11         2         6        1         7        11
 2            38        8         5         6        5         4        10
 3            38        9         7         3        7         5         7
 4            38        7         8         4        3         6        10
 5            38        8         3         8        6         4         9
 6            38       12         5         2        7         5         7
 7            38       11         5         3        6         3        10
 8            38       11         3         5        2         6        11
 9            38        7         3         9        7         2        10
 10           38        9         8         2        9         2         8
 11           38        9         2         8        6         4         9
 12           38       16         2         1        9         6         4
 13           38       10         7         2        3         3        13
 14           38       15         2         2        6         4         9
 15           38        9         8         2        4         5        10
 16           38        3         2        14        1         5        13
 17           38        9         4         6        5         4        10
 18           38        3         5        11        3         3        13
 19           38        5         7         7        5         5         9

     winsagg  drawsagg  lossagg
 0        23         9        6
 1        12         9       17
 2        13         9       16
 3        16        12       10
 4        10        14       14
 5        14         7       17
 6        19        10        9
 7        17         8       13
 8        13         9       16
 9        14         5       19
 10       18        10       10
 11       15         6       17
 12       25         8        5
 13       13        10       15
 14       21         6       11
 15       13        13       12
 16        4         7       27
 17       14         8       16
 18        6         8       24
 19       10        12       16  ,
              Team  HGS  HGC  AGS  AGC   HS   AS  HST  AST   HF   AF   HC   AC  \
 0         Arsenal   40   14   33   12  260  211  151  122  236  263  118   84
 1     Aston Villa   24   19   24   25  240  205  130  100  282  270  132  116
 2      Birmingham   26   24   17   24  185  143  106   70  251  254  111   74
 3       Blackburn   25   31   26   28  250  201  135   97  231  282  129   98
 4          Bolton   24   21   24   35  310  223  177  113  231  230  155   83
 5        Charlton   29   29   22   22  216  168  116   84  226  242  109   92
 6         Chelsea   34   13   33   17  254  227  122  122  202  240  126  102
 7         Everton   27   20   18   37  262  168  137   78  222  236  132  110
 8          Fulham   29   21   23   25  213  189  118  103  265  248   92   68
 9           Leeds   25   31   15   48  210  152  107   74  278  264  106   93
 10      Leicester   19   28   29   37  212  154  129   85  258  265  121   87
 11      Liverpool   29   15   26   22  304  254  156  144  223  230  147  113
 12       Man City   31   24   24   30  300  215  164  128  181  244  131   90
 13     Man United   37   15   27   20  259  235  142  142  203  226  115  100
 14  Middlesbrough   25   23   19   29  261  200  148  106  237  260  106   71
 15      Newcastle   33   14   19   26  280  168  166   96  247  239  142   95
 16     Portsmouth   35   19   12   35  235  168  134   83  254  296  109   84
 17    Southampton   24   17   20   28  249  208  145  120  236  215  100  121
 18      Tottenham   33   27   14   30  250  171  142   92  253  311  103   95
 19         Wolves   23   35   15   42  210  188  102   89  226  236  101   77

     HY  AY  HR  AR  totalpoints  TGS  TGC  GD  homepoints  awaypoints  \
 0   23  29   1   2           90   73   26  47          49          41
 1   23  29   0   3           56   48   44   4          33          23
 2   24  21   3   2           50   43   48  -5          29          21
 3   28  33   1   2           44   51   59  -8          19          25
 4   31  35   0   0           53   48   56  -8          26          27
 5   20  16   2   1           53   51   51   0          27          26
 6   17  28   2   1           79   67   30  37          40          39
 7   27  26   1   2           39   45   57 -12          29          10
 8   26  35   2   1           52   52   46   6          31          21
 9   34  37   3   2           33   40   79 -39          22          11
 10  25  34   2   5           33   48   65 -17          19          14
 11  16  31   0   1           60   55   37  18          34          26
 12  19  28   1   2           41   55   54   1          24          17
 13  20  23   0   3           75   64   35  29          40          35
 14  27  30   0   1           48   44   52  -8          28          20
 15  17  29   0   3           56   52   40  12          38          18
 16  26  36   0   3           45   47   54  -7          34          11
 17  27  25   1   2           47   44   45  -1          30          17
 18  21  39   0   1           45   47   57 -10          31          14
 19  30  36   1   1           33   38   77 -39          26           7

     gamesplayed  homewin  homedraw  homeloss  awaywin  awaydraw  awayloss  \
 0            38       15         4         0       11         8         0
 1            38        9         6         4        6         5         8
 2            38        8         5         6        4         9         6
 3            38        5         4        10        7         4         8
 4            38        6         8         5        8         3         8
 5            38        7         6         6        7         5         7
 6            38       12         4         3       12         3         4

In [83]:
winpct(y20list)

TypeError: list indices must be integers or slices, not str

# new question????

In [ ]:
# doesnt work 
# pd.set_option('display.max_rows', None)
# test = test.sort_values(['Points'], axis=0, ascending=False)
# test

In [ ]:
# group by home team for total goal scored at home
# same away 
# add togetehr 

# date change 

# group by home team, home points
# group by away team, away points
# add together 
# = points total 

# home table/df 
# away table/df

# key column?

# if fthg > ftag ht win and assign total goals

# loop using the first 380 
# if fthg > ftag 

# can it do it without the score ?

# total shots, goal, yc, rc, posts, on target, off target, offsides etc

# wins draws losses columns?

# is tehre relationship between results / points
# home goals/wins to points
# home wins 50%?
# home gmae adv ?

In [ ]:
# new question 
# is there a quanitfiable home team advantage in the Premier league 
# home wins/draw/losses count

# goals scored and conceded

# games played

# won drew loss x games home/away

In [ ]:
# if away win append 1 to the away list
# append 0 home list
# append 0 draw list

# change data to model

In [ ]:
# need to use games not season results?

In [ ]:
modelist = [y0001,y0102,y0203,y0304,y0405,y0506,y0607,y0708,y0809,y0910,y1011,y1112,y1213,y1314,y1415,y1516,y1617,y1718,y1819,y1920,y2021,y2122]

In [ ]:
bigtable = pd.concat(modelist, axis=0)

In [ ]:
# get everything into uniform cols
# columnsreq = [['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
#  'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]

In [ ]:
bigtable = bigtable[['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]

In [ ]:
bigtable

In [ ]:
# def only_hw(string):
#     if string == 'H':
#         return 'H'
#     else:
#         return 'NH'
    
# bigtable['FTR'] = bigtable.FTR.apply(only_hw)

In [ ]:
bigtable

In [ ]:
# bigtable.loc[bigtable['FTR'].str.contains('H'),'FTR']=0

# bigtable.loc[bigtable['FTR'].str.contains('A'),'FTR']=1

# bigtable.loc[bigtable['FTR'].str.contains('D'),'FTR']=1

In [ ]:
bigtable['FTR'] = bigtable['FTR'].map({'H': 1, 'D': 0, 'A': 0})
# 1 is home win, 0 is not home win

In [ ]:
# fthg ag out

# messing around with years

In [ ]:
bigtable['year'] = pd.DatetimeIndex(bigtable['Date']).year
# y1617.head()

In [ ]:
arsenal01 = y0001[y0001['Team']=='Arsenal']

In [ ]:
arsenal01

In [ ]:
arsena2 = sr0102[sr0102['Team']=='Arsenal']

In [ ]:
arsena2

# Models

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# linear regression?
# logistic?
# MLPregressor?
# Random forest?
# Knn? maybe no 
# xgboost?

In [ ]:

y = bigtable['FTR']
X = bigtable.drop(['FTR','HomeTeam','AwayTeam', 'FTHG', 'FTAG'],axis=1)

In [ ]:
# take out columns, FTHG/FTAG was giving models the answer, have to remove

In [ ]:
plt.figure(figsize=(20,10)) 
sns.heatmap(bigtable.corr(), annot= True)

In [ ]:
# htag,hthg,hs,as,hst,ast have high correlations

In [ ]:
# pd.plotting.scatter_matrix(X, figsize=(20,10))

In [ ]:
# plot ftr (target) against ast/hst

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
lm = linear_model.LinearRegression()
lm.fit(X_train, y_train)
print('score', lm.score(X_train,y_train))

In [ ]:
# score wont chnage after scaling, the ranges arent big enough

In [ ]:


Xnumtrain = X_train.select_dtypes(np.number)
Xnumtest = X_test.select_dtypes(np.number)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(Xnumtrain)
Xnumtrainscale = transformer.transform(Xnumtrain)
Xnumtestscale = transformer.transform(Xnumtest)

In [ ]:
X_train_processed = pd.DataFrame(Xnumtrainscale, columns=Xnumtrain.columns)

In [ ]:
X_test_processed = pd.DataFrame(Xnumtestscale, columns=Xnumtest.columns)

In [ ]:
# X_train_processed = pd.DataFrame((Xnumtrain,Xcattrain),axis=1)
# X_test_processed = pd.DataFrame((Xnumtest,Xcattest),axis=1)

In [ ]:
X_train_processed

In [ ]:
X_test_processed

# Linear regression

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
lm = linear_model.LinearRegression()
lm.fit(X_train_processed, y_train)
print('score', lm.score(X_train_processed,y_train))

# Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_processed, y_train)

In [ ]:
Y_predlog = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, Y_predlog)

In [ ]:
sns.heatmap(cm, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test, Y_predlog))

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

KNN = KNeighborsRegressor(n_neighbors=3)
KNN.fit(X_train_processed, y_train)

In [ ]:
score_train = KNN.score(X_train_processed, y_train)
score_train          #R2 score

In [ ]:
score = KNN.score(X_test_processed, y_test)
score                #R2 score

In [ ]:
KNN2 = KNeighborsRegressor(n_neighbors=2)
KNN2.fit(X_train_processed, y_train)

In [ ]:
score_train2 = KNN2.score(X_train_processed, y_train)
score_train2          #R2 score

In [ ]:
score2 = KNN2.score(X_test_processed, y_test)
score2                #R2 score

In [ ]:
# closest rows in stats could have different end results 
# (high shots team vs low bloc defenders = huge shots but no goals)

# teams with identical enough game stats having opposite end results, very possible
# 8000+games checking neighbours probably not as useful for predicting

# SVC model

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state = 0)
classifier.fit(X_train_processed, y_train)

In [ ]:
Y_predsvc = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix
cmsvc = confusion_matrix(y_test, Y_predsvc)

In [ ]:
sns.heatmap(cmsvc, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test, Y_predsvc))

# RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_processed, y_train)

In [ ]:
#predicting result
Y_predrfc1 = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc1 = confusion_matrix(y_test, Y_predrfc1)

In [ ]:
sns.heatmap(cmrfc1, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test, Y_predrfc1))

In [ ]:
# change parameters to compare results

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(criterion='gini', 
                             n_estimators=700,
                             min_samples_split=10,
                             min_samples_leaf=1,
                             max_features='sqrt',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1)
classifier.fit(X_train_processed, y_train)

In [ ]:
#predicting result
Y_predrfc = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc = confusion_matrix(y_test, Y_predrfc)

In [ ]:
sns.heatmap(cmrfc, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test, Y_predrfc))

# XGBOOST

In [ ]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier(seed=82)
classifier.fit(X_train_processed, y_train)

In [ ]:
# Predicting the Test set results
Y_predx = classifier.predict(X_test_processed)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmx = confusion_matrix(y_test, Y_predx)

In [ ]:
sns.heatmap(cmx, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test, Y_predx))

In [ ]:
# can I boost the xgboost?

# MLPregressor

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp=MLPRegressor(random_state=1, max_iter=500)
mlp.fit(X_train_processed, y_train)

In [ ]:
# Predicting the Test set results
Y_predmlp = classifier.predict(X_test_processed)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmlp = confusion_matrix(y_test, Y_predmlp)

In [ ]:
sns.heatmap(cmlp, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test, Y_predmlp))

# Can we predict a home win?

In [ ]:
# in general with the more aacurate scoring models we can predict a home win around 70% of the time

In [ ]:
# is this useful? or interesting?

# Models with half time goals ?

In [ ]:
# modelist = [y0001,y0102,y0203,y0304,y0405,y0506,y0607,y0708,y0809,y0910,y1011,y1112,y1213,y1314,y1415,y1516,y1617,y1718,y1819,y1920,y2021,y2122]

In [ ]:
secondmodel = pd.concat(modelist, axis=0)

In [ ]:
secondmodel = secondmodel[['HomeTeam', 'AwayTeam', 'HTHG', 'HTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]

In [ ]:
secondmodel

In [ ]:
secondmodel['FTR'] = secondmodel['FTR'].map({'H': 1, 'D': 0, 'A': 0})

In [ ]:
secondmodel

In [ ]:
secondmodel.isna().sum()

In [ ]:
secondmodel=secondmodel.dropna()

In [ ]:
secondmodel.isna().sum()

In [ ]:
# weird

# Models again

In [ ]:
# keeping half time goals in to see if it helps the mdoel decide home win/not

In [ ]:

y2 = secondmodel['FTR']
X2 = secondmodel.drop(['FTR','HomeTeam','AwayTeam'],axis=1)

In [ ]:
plt.figure(figsize=(20,10)) 
sns.heatmap(secondmodel.corr(), annot= True)

In [ ]:
from sklearn.model_selection import train_test_split 
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.2, random_state=42)

In [ ]:

Xnumtrain2 = X_train2.select_dtypes(np.number)
Xnumtest2 = X_test2.select_dtypes(np.number)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(Xnumtrain2)
Xnumtrainscale2 = transformer.transform(Xnumtrain2)
Xnumtestscale2 = transformer.transform(Xnumtest2)

In [ ]:
X_train_processed2 = pd.DataFrame(Xnumtrainscale2, columns=Xnumtrain2.columns)
X_test_processed2 = pd.DataFrame(Xnumtestscale2, columns=Xnumtest2.columns)

In [ ]:
X_train_processed2

In [ ]:
X_test_processed2

# Linear regression

In [ ]:
# first linear regression score was crap so dont do it again
# i dont think its a linear problem anyway

# Logistic

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_processed2, y_train2)

In [ ]:
Y_predlog2 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
cmlog2 = confusion_matrix(y_test2, Y_predlog2)

In [ ]:
sns.heatmap(cmlog2, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predlog2))

# KNN

In [ ]:
# didnt like knn results last time so not doing again

# SVC

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state = 0)
classifier.fit(X_train_processed2, y_train2)

In [ ]:
Y_predsvc2 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix
cmsvc2 = confusion_matrix(y_test2, Y_predsvc2)

In [ ]:
sns.heatmap(cmsvc2, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predsvc2))

# RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_processed2, y_train2)

In [ ]:
#predicting result
Y_predrfc12 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc12 = confusion_matrix(y_test2, Y_predrfc12)

In [ ]:
sns.heatmap(cmrfc12, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predrfc12))

In [ ]:
# parameter fiddling

In [ ]:
from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier = RandomForestClassifier(criterion='gini', 
                             n_estimators=700,
                             min_samples_split=10,
                             min_samples_leaf=1,
                             max_features='sqrt',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1)
classifier.fit(X_train_processed2, y_train2)

In [ ]:
#predicting result
Y_predrfc2 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc2 = confusion_matrix(y_test2, Y_predrfc2)

In [ ]:
sns.heatmap(cmrfc2, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predrfc2))

# XGBOOST

In [ ]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier(seed=82)
classifier.fit(X_train_processed2, y_train2)

In [ ]:
# Predicting the Test set results
Y_predx2 = classifier.predict(X_test_processed2)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmx2 = confusion_matrix(y_test2, Y_predx2)

In [ ]:
sns.heatmap(cmx2, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predx2))

In [ ]:
# scores become slightly better, as the half time result != full time result in many cases, 
# strong enough indicator of who is going to win that the accuracy scores increase a litte bit however

# MLPregressor

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp2=MLPRegressor(random_state=1, max_iter=500)
mlp2.fit(X_train_processed2, y_train2)

In [ ]:
# Predicting the Test set results
Y_predmlp2 = classifier.predict(X_test_processed2)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmlp2 = confusion_matrix(y_test2, Y_predmlp2)

In [ ]:
sns.heatmap(cmlp2, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predmlp2))

# to csv

In [ ]:
y6.to_csv('y6.csv', index=False)

In [ ]:
y20.to_csv('y20.csv', index=False)

In [ ]:
distable.to_csv('distable.csv', index=False)

In [ ]:
top6.to_csv('top6.csv', index=False)

In [ ]:
nottop6.to_csv('nottop6.csv', index=False)

In [ ]:
bigtable.to_csv('bigtable.csv', index=False)

In [ ]:
# done already

# SQL

In [ ]:
# import pymysql
# from sqlalchemy import create_engine
# import getpass  # To get the password without showing the input

# password = getpass.getpass()

In [ ]:
# # get the data
# connection_string = 'mysql+pymysql://root:' + password + '@localhost/midpro'
# engine = create_engine(connection_string)

In [ ]:
# distable.to_sql('distable', con=engine)
# # do this again

In [ ]:
# y6.to_sql('y6', con=engine)

In [ ]:
# y20.to_sql('y20', con=engine)

In [ ]:
# top6.to_sql('top6', con=engine)

In [ ]:
# nottop6.to_sql('nottop6', con=engine)

In [ ]:
# bigtable.to_sql('bigtable', con=engine)

In [ ]:
# secondmodel.to_sql('secondmodel', con=engine)

In [ ]:
# query = 'select * from distable'
# sqlproof = pd.read_sql_query(query, engine)
# sqlproof.head()

In [ ]:
# done