# Mid Bootcamp Project

1. Formulate question
2. Find data
3. Clean data using Python
4. Store clean data in both a .csv file and a MySQL Database
5. Exploratory Analysis, reading data from MySQL
6. Visualize data using Tableau
7. Create and test (at least one) hypothesis
   (optional: build a Machine Learning model
   But only if it helps answer your research question)
8. Formulate conclusions / answers
9. Prepare presentation
10. Present

Question: does the home team win over 50% of games in the English Premier League

In [1]:
# hyp test

In [2]:
import pandas as pd
import numpy as np

In [3]:
# https://www.kaggle.com/datasets/saife245/english-premier-league?select=Datasets

In [4]:
# Key to results data:

# Div = League Division
# Date = Match Date (dd/mm/yy)
# Time = Time of match kick-off
# HomeTeam = Home Team
# Away team = Away Team
# FTHG and HG = Full Time Home Team Goals
# FTAG and AG = Full-Time Away Team Goals
# FTR and Res = Full-Time Result (H=Home Win, D=Draw, A=Away Win)
# HTHG = Half Time Home Team Goals
# HTAG = Half Time Away Team Goals
# HTR = Half Time Result (H=Home Win, D=Draw, A=Away Win)

# Match Statistics (where available)
# Attendance = Crowd Attendance
# Referee = Match Referee
# HS = Home Team Shots
# AS = Away Team Shots
# HST = Home Team Shots on Target
# AST = Away Team Shots on Target
# HHW = Home Team Hit Woodwork
# AHW = Away Team Hit Woodwork
# HC = Home Team Corners
# AC = Away Team Corners
# HF = Home Team Fouls Committed
# AF = Away Team Fouls Committed
# HFKC = Home Team Free Kicks Conceded
# AFKC = Away Team Free Kicks Conceded
# HO = Home Team Offsides
# AO = Away Team Offsides
# HY = Home Team Yellow Cards
# AY = Away Team Yellow Cards
# HR = Home Team Red Cards
# AR = Away Team Red Cards

In [5]:
# pd.set_option('display.max_columns', None)

# Taking a look at my data

In [6]:
y0001 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2000-01.csv')
y0102 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2001-02.csv')
y0203 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2002-03.csv')
y0304 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2003-04.csv')
y0405 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2004-05.csv')
y0506 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2005-06.csv')
y0607 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2006-07.csv')
y0708 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2007-08.csv')
y0809 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2008-09.csv')
y0910 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2009-10.csv')
y1011 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2010-11.csv')
y1112 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2011-12.csv')
y1213 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2012-13.csv')
y1314 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2013-14.csv')
y1415 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2014-15.csv')
y1516 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2015-16.csv')
y1617 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2016-17.csv')
y1718 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2017-18.csv')
y1819 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2018-19.csv')
y1920 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2019-20.csv')
y2021 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2020-2021.csv')
y2122 = pd.read_csv('/Users/lucaalfano/IH-labs/midcampproject/Datasets/2021-2022.csv')

In [7]:
y1617

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,13/08/16,Burnley,Swansea,0,1,A,0,0,D,...,1.61,32,-0.25,2.13,2.06,1.86,1.81,2.79,3.16,2.89
1,E0,13/08/16,Crystal Palace,West Brom,0,1,A,0,0,D,...,1.52,33,-0.50,2.07,2.00,1.90,1.85,2.25,3.15,3.86
2,E0,13/08/16,Everton,Tottenham,1,1,D,1,0,H,...,1.77,32,0.25,1.91,1.85,2.09,2.00,3.64,3.54,2.16
3,E0,13/08/16,Hull,Leicester,2,1,H,1,0,H,...,1.67,31,0.25,2.35,2.26,2.03,1.67,4.68,3.50,1.92
4,E0,13/08/16,Man City,Sunderland,2,1,H,1,0,H,...,2.48,34,-1.50,1.81,1.73,2.20,2.14,1.25,6.50,14.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,21/05/17,Liverpool,Middlesbrough,3,0,H,1,0,H,...,2.73,18,-2.50,2.02,1.97,1.95,1.90,1.15,10.50,19.09
376,E0,21/05/17,Man United,Crystal Palace,2,0,H,2,0,H,...,1.81,19,-0.25,2.19,2.11,1.85,1.79,2.35,3.38,3.35
377,E0,21/05/17,Southampton,Stoke,0,1,A,0,0,D,...,2.01,18,-0.75,2.03,1.98,1.93,1.88,1.64,4.37,5.53
378,E0,21/05/17,Swansea,West Brom,2,1,H,0,1,A,...,1.98,19,-0.50,2.11,2.06,1.86,1.82,2.29,3.45,3.40
379,E0,21/05/17,Watford,Man City,0,5,A,0,4,A,...,2.80,18,1.75,1.99,1.94,2.00,1.93,18.00,9.70,1.16

# What can i do with this?

In [8]:
# drop betting columns from newer datasets
# i dont think i will use them at all 
# 
# make an average table position out of eplstandings?
# use this average table position in some way?
# 
# 
# 
# make dfs with same columns, dropping betting odds 
# concat ?

# group by hometeam agg func home goals sum

In [9]:
# make a function to keep certain columns and drop the rest, axis=0 to concat on top of eachother ?

In [10]:
columnsreq = ['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']

In [11]:
list(y1617.columns.values.tolist())

['Div',
 'Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'Bb1X2',
 'BbMxH',
 'BbAvH',
 'BbMxD',
 'BbAvD',
 'BbMxA',
 'BbAvA',
 'BbOU',
 'BbMx>2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'BbAv<2.5',
 'BbAH',
 'BbAHh',
 'BbMxAHH',
 'BbAvAHH',
 'BbMxAHA',
 'BbAvAHA',
 'PSCH',
 'PSCD',
 'PSCA']

In [12]:
# columns ['Date', 'HomeTeam', 'AwayTeam', 'FTHG','FTAG','FTR','HTHG','HTAG','HS','AS','HST','AST',
#  'HF', 'AF','HC','AC','HY','AY','HR','AR']

In [13]:
y1617 = y1617[columnsreq]
# pd.set_option('display.max_columns', None)

In [14]:
y1617

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,13/08/16,Burnley,Swansea,0,1,A,10,17,3,9,10,14,7,4,3,2,0,0
1,13/08/16,Crystal Palace,West Brom,0,1,A,14,13,4,3,12,15,3,6,2,2,0,0
2,13/08/16,Everton,Tottenham,1,1,D,12,13,6,4,10,14,5,6,0,0,0,0
3,13/08/16,Hull,Leicester,2,1,H,14,18,5,5,8,17,5,3,2,2,0,0
4,13/08/16,Man City,Sunderland,2,1,H,16,7,4,3,11,14,9,6,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,21/05/17,Liverpool,Middlesbrough,3,0,H,25,9,10,3,13,8,3,3,0,1,0,0
376,21/05/17,Man United,Crystal Palace,2,0,H,9,6,2,1,16,10,3,6,2,0,0,0
377,21/05/17,Southampton,Stoke,0,1,A,14,14,6,3,12,10,4,10,2,4,0,0
378,21/05/17,Swansea,West Brom,2,1,H,12,16,2,5,8,10,7,4,1,1,0,0
379,21/05/17,Watford,Man City,0,5,A,6,15,3,9,12,10,4,5,1,0,0,0

In [15]:
# get points from HTR? 3 points to home/ 1 each draw

In [16]:
# if fthg > ftag then 3 points home team elif ftag > fthg 3 points away else fthg = ftag 1 point each 
# split columns?

In [17]:
# the data set is big, 
# just use years 2016/17 - 21/22?
# y1617

In [18]:
# hometeamgames

In [19]:
# hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})

In [20]:
# hometeamgames

In [21]:
# homegamesresults = hometeamgames.groupby('HomeTeam').sum().reset_index()

In [22]:
# homegamesresults = homegamesresults.rename(columns={'FTHG':'HGS', 'FTAG':'HGC'})

In [23]:
# ratio of shots to goal ?

In [24]:
def bigfunc(df):


    # organizing, renaming cols, and attributing points to winner/home
    hometeamgames = df[['Date', 'HomeTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'HST', 'HF', 'HC', 'HY', 'HR']]
    
    hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
    
    homewin = []
    homedraw = []
    homeloss = []
    
    for i in hometeamgames['FTR']:
        if 'A' in i:
            homewin.append(0)
            homedraw.append(0)
            homeloss.append(1)
        elif 'D' in i:
            homewin.append(0)
            homedraw.append(1)
            homeloss.append(0)
        elif 'H' in i:
            homewin.append(1)
            homedraw.append(0)
            homeloss.append(0)
    hometeamgames['homewin'] = homewin
    hometeamgames['homedraw'] = homedraw
    hometeamgames['homeloss'] = homeloss
    
    homegamesresults = hometeamgames.groupby('HomeTeam').sum().reset_index()

    homegamesresults = homegamesresults.rename(columns={'FTHG':'HGS', 'FTAG':'HGC'})
    
    homegamesresults['homeplayed'] = homegamesresults['homewin']+homegamesresults['homedraw']+homegamesresults['homeloss']
    
    
    
    
    
    # organizing, renaming cols, and attributing points to winner/away
    awayteamgames = df[['Date', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'AS', 'AST', 'AF', 'AC', 'AY', 'AR']]
    
    awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
    
    awaywin = []
    awaydraw = []
    awayloss = []
    
    for i in awayteamgames['FTR']:
        if 'A' in i:
            awaywin.append(1)
            awaydraw.append(0)
            awayloss.append(0)
        elif 'D' in i:
            awaywin.append(0)
            awaydraw.append(1)
            awayloss.append(0)
        elif 'H' in i:
            awaywin.append(0)
            awaydraw.append(0)
            awayloss.append(1)
    awayteamgames['awaywin'] = awaywin
    awayteamgames['awaydraw'] = awaydraw
    awayteamgames['awayloss'] = awayloss
        
    awaygamesresults = awayteamgames.groupby('AwayTeam').sum().reset_index()
    
    awaygamesresults = awaygamesresults.rename(columns={'FTHG':'AGC', 'FTAG':'AGS'})
    
    awaygamesresults['awayplayed'] = awaygamesresults['awaywin']+awaygamesresults['awaydraw']+awaygamesresults['awayloss']
    
    
    
    
    # back together to find season totals 
    seasonresults = pd.concat([homegamesresults, awaygamesresults], axis=1)
    
    
    # agg cols 
    seasonresults['totalpoints'] = seasonresults['homepoints']+seasonresults['awaypoints']
    
    seasonresults['gamesplayed'] = seasonresults['homeplayed'] + seasonresults['awayplayed']
    
    seasonresults['TGS'] = seasonresults['HGS']+seasonresults['AGS']
    
    seasonresults['TGC'] = seasonresults['HGC']+seasonresults['AGC']
    
    seasonresults['GD'] = seasonresults['TGS']-seasonresults['TGC']

    seasonresults = seasonresults.rename(columns={'HomeTeam':'Team'})

    #ratios 
    
    seasonresults['winsagg'] = seasonresults['homewin']+seasonresults['awaywin']
    seasonresults['drawsagg'] = seasonresults['homedraw']+seasonresults['awaydraw']
    seasonresults['lossagg'] = seasonresults['homeloss']+seasonresults['awayloss']
    
#     seasonresults['win%'] = round((seasonresults['winsagg']/seasonresults['gamesplayed']*100),1)
#     seasonresults['draw%'] = round((seasonresults['drawsagg']/seasonresults['gamesplayed']*100),1)
#     seasonresults['loss%'] = round((seasonresults['lossagg']/seasonresults['gamesplayed']*100),1)

    seasonresults = seasonresults[['Team', 'HGS', 'HGC', 'AGS', 'AGC','HS', 'AS', 'HST', 'AST', 'HF','AF','HC','AC', 'HY', 'AY', 'HR', 'AR' , 'totalpoints', 'TGS', 'TGC', 'GD', 'homepoints', 'awaypoints', 'gamesplayed', 'homewin', 'homedraw', 'homeloss', 'awaywin', 'awaydraw', 'awayloss','winsagg','drawsagg','lossagg']]

    return seasonresults

In [25]:
sr1617=bigfunc(y1617)
sr1718=bigfunc(y1718)
sr1819=bigfunc(y1819)
sr1920=bigfunc(y1920)
sr2021=bigfunc(y2021)
sr2122=bigfunc(y2122)

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

In [26]:
y6list = [sr1617,sr1718,sr1819,sr1920,sr2021,sr2122]

In [27]:
y6 = pd.concat(y6list,axis=0).reset_index(drop=True)

In [28]:
pd.set_option('display.max_columns', None)

In [29]:
y6.groupby('Team').sum().reset_index()

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
0,Arsenal,191,100,147,136,1551,1160,558,405,1019,944,659,463,162,163,8,9,336,338,236,102,201,135,194,61,18,19,38,21,37,99,39,56
1,Aston Villa,76,80,65,70,691,612,237,226,576,562,289,258,84,104,5,1,125,141,150,-9,65,60,102,18,11,22,18,6,27,36,17,49
2,Bournemouth,90,92,61,102,759,604,255,211,540,548,322,307,97,86,5,3,139,151,194,-43,87,52,118,24,15,21,13,13,32,37,28,53
3,Brentford,22,21,26,35,233,209,77,77,187,184,88,71,29,32,2,1,46,48,56,-8,24,22,38,7,3,9,6,4,9,13,7,18
4,Brighton,94,92,72,112,1024,812,289,278,852,869,424,341,136,104,4,10,180,166,204,-38,104,76,156,24,32,21,18,22,39,42,54,60
5,Burnley,99,122,88,151,1066,890,345,286,987,1012,466,376,151,171,0,4,214,187,273,-86,124,90,194,34,22,41,21,27,49,55,49,90
6,Cardiff,12,15,3,15,130,56,31,20,90,67,47,24,17,8,0,1,14,15,30,-15,13,1,16,4,1,4,0,1,6,4,2,10
7,Chelsea,188,94,169,95,1661,1370,613,466,993,1017,678,497,139,158,5,3,379,357,189,168,194,185,194,57,23,18,56,17,23,113,40,41
8,Crystal Palace,114,122,108,163,1142,979,379,331,1064,1115,496,444,162,175,2,3,219,222,285,-63,119,100,194,31,26,39,25,25,48,56,51,87
9,Everton,155,114,98,159,1238,1021,438,359,1055,1103,538,396,158,162,8,10,268,253,273,-20,170,98,194,50,20,28,24,26,46,74,46,74
10,Fulham,19,44,24,49,356,286,101,100,317,351,129,103,47,44,3,2,37,43,93,-50,18,19,54,4,6,16,3,10,15,7,16,31
11,Huddersfield,19,35,19,50,287,251,76,86,264,313,133,97,33,53,4,1,47,38,85,-47,28,19,54,7,7,13,4,7,16,11,14,29
12,Hull,28,35,9,45,208,188,69,58,219,184,73,106,32,35,2,3,34,37,80,-43,28,6,38,8,4,7,1,3,15,9,7,22
13,Leeds,47,59,57,74,529,478,182,171,463,433,214,188,86,75,2,2,97,104,133,-29,47,50,76,12,11,15,15,5,18,27,16,33
14,Leicester,160,122,149,156,1235,1090,443,415,982,1032,552,485,126,164,4,8,281,309,278,31,161,120,194,47,20,30,32,24,41,79,44,71
15,Liverpool,218,67,201,102,1740,1514,635,560,906,972,672,606,101,129,1,3,430,419,169,250,224,206,194,68,20,8,61,23,14,129,43,22
16,Man City,262,80,218,82,1838,1594,674,574,889,937,787,680,121,158,7,5,452,480,162,318,231,221,194,72,15,10,69,14,14,141,29,24
17,Man United,172,94,146,119,1499,1223,557,479,1095,1143,585,484,168,194,3,5,346,318,213,105,185,161,194,52,29,16,45,26,26,97,55,42
18,Middlesbrough,17,23,10,30,205,144,59,41,210,268,93,48,38,38,0,1,28,27,53,-26,18,10,38,4,6,9,1,7,11,5,13,20
19,Newcastle,92,104,74,129,960,766,306,272,846,775,353,309,124,132,7,3,182,166,233,-67,107,75,156,29,20,30,19,18,40,48,38,70
20,Norwich,30,69,17,63,362,317,123,86,305,303,163,124,53,50,1,2,40,47,132,-85,24,16,64,6,6,20,3,7,22,9,13,42
21,Sheffield United,27,39,21,48,339,249,110,75,367,380,184,131,56,68,2,2,62,48,87,-39,36,26,64,11,3,18,6,8,18,17,11,36
22,Southampton,108,136,105,181,1277,1191,431,420,1043,1115,543,518,138,171,7,5,205,213,317,-104,111,94,194,27,30,39,23,25,50,50,55,89
23,Stoke,44,54,32,70,432,376,144,124,441,429,183,141,65,67,3,0,77,76,124,-48,47,30,76,12,11,15,6,12,20,18,23,35
24,Sunderland,16,34,13,35,214,173,66,55,221,216,86,74,35,41,2,2,24,29,69,-40,14,10,38,3,5,11,3,1,15,6,6,26
25,Swansea,44,58,29,68,437,289,152,98,386,392,214,132,54,53,0,1,74,73,126,-53,48,26,76,14,6,18,6,8,24,20,14,42
26,Tottenham,196,82,174,115,1484,1264,559,493,1028,1056,589,502,133,173,3,6,372,370,197,173,207,165,194,65,12,18,47,24,28,112,36,46
27,Watford,93,136,69,136,964,778,294,252,963,929,372,346,168,119,8,9,149,162,272,-110,89,60,156,24,17,37,15,15,48,39,32,85
28,West Brom,63,90,46,93,604,511,196,153,654,639,281,198,94,109,2,3,102,109,183,-74,62,40,114,15,17,25,8,16,33,23,33,58
29,West Ham,142,144,128,156,1194,1028,406,370,958,953,500,404,175,149,2,13,253,270,300,-30,143,110,194,40,23,35,29,23,44,69,46,79
30,Wolves,69,78,57,68,762,647,241,226,651,631,312,292,95,88,1,3,154,126,146,-20,78,76,118,21,15,23,20,16,23,41,31,46

In [30]:
sr0001 = bigfunc(y0001)
sr0102 = bigfunc(y0102)
sr0203 = bigfunc(y0203)
sr0304 = bigfunc(y0304)
sr0405 = bigfunc(y0405)
sr0506 = bigfunc(y0506)
sr0607 = bigfunc(y0607)
sr0708 = bigfunc(y0708)
sr0809 = bigfunc(y0809)
sr0910 = bigfunc(y0910)
sr1011 = bigfunc(y1011)
sr1112 = bigfunc(y1112)
sr1213 = bigfunc(y1213)
sr1314 = bigfunc(y1314)
sr1415 = bigfunc(y1415)
sr1516 = bigfunc(y1516)
sr1617 = bigfunc(y1617)
sr1718 = bigfunc(y1718)
sr1819 = bigfunc(y1819)
sr1920 = bigfunc(y1920)
sr2021 = bigfunc(y2021)
sr2122 = bigfunc(y2122)

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})

/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homepoints'] = hometeamgames['FTR'].map({'H': 3, 'D': 1, 'A': 0})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homewin'] = homewin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homedraw'] = homedraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hometeamgames['homeloss'] = homeloss
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaypoints'] = awayteamgames['FTR'].map({'H': 0, 'D': 1, 'A': 3})
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaywin'] = awaywin
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awaydraw'] = awaydraw
/var/folders/3k/_2nrg4_92wv7dq340pkrhc5h0000gn/T/ipykernel_17290/660866032.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  awayteamgames['awayloss'] = awayloss

In [31]:
y20list = [sr0001,sr0102,sr0203,sr0304,sr0405,sr0506,sr0607,sr0708,sr0809,sr0910,sr1011,sr1112,sr1213,sr1314,sr1415,sr1516,sr1617,sr1718,sr1819,sr1920,sr2021,sr2122]

In [32]:
y20 = pd.concat(y20list,axis=0).reset_index(drop=True)

In [33]:
y20.groupby('Team').sum().reset_index()

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
0,Arsenal,853,353,650,478,6355,4939,3163,2376,4345,4418,2956,2097,551,677,24,46,1545,1503,831,672,888,657,802,268,84,50,184,105,111,452,189,161
1,Aston Villa,453,421,406,571,4227,3609,1918,1703,4190,4586,2182,1766,502,683,25,23,875,859,992,-133,497,378,710,130,107,118,93,99,163,223,206,281
2,Birmingham,162,140,111,220,1365,1064,707,549,1634,1687,748,565,191,241,13,14,301,273,360,-87,196,105,266,50,46,37,23,36,74,73,82,111
3,Blackburn,289,239,229,353,2645,2000,1343,1047,2886,2848,1206,1036,342,411,23,27,530,518,592,-74,317,213,418,86,59,64,54,51,104,140,110,168
4,Blackpool,30,37,25,41,253,193,134,101,216,187,94,92,22,25,0,2,39,55,78,-23,20,19,38,5,5,9,5,4,10,10,9,19
5,Bolton,278,260,217,353,2787,2003,1546,1010,2617,2765,1288,970,296,428,17,19,506,495,613,-118,306,200,418,81,63,65,51,47,111,132,110,176
6,Bournemouth,113,126,83,135,1002,824,338,272,715,735,451,399,122,113,5,4,181,196,261,-65,107,74,156,29,20,30,19,17,41,48,37,71
7,Bradford,20,29,10,41,221,150,101,73,255,262,108,71,27,30,0,1,26,30,70,-40,19,7,38,4,7,8,1,4,14,5,11,22
8,Brentford,22,21,26,35,233,209,77,77,187,184,88,71,29,32,2,1,46,48,56,-8,24,22,38,7,3,9,6,4,9,13,7,18
9,Brighton,94,92,72,112,1024,812,289,278,852,869,424,341,136,104,4,10,180,166,204,-38,104,76,156,24,32,21,18,22,39,42,54,60
10,Burnley,138,173,119,235,1514,1277,532,452,1406,1433,656,536,204,239,0,8,277,257,408,-151,169,108,270,45,34,56,25,33,77,70,67,133
11,Cardiff,32,50,15,54,358,247,105,72,257,242,157,110,42,32,0,2,44,47,104,-57,33,11,54,9,6,13,2,5,19,11,11,32
12,Charlton,179,178,122,208,1436,1087,772,552,1639,1644,731,619,158,180,13,8,325,301,386,-85,195,130,266,54,33,46,31,37,65,85,70,111
13,Chelsea,838,331,644,382,6579,5417,3061,2469,4399,4562,2721,2256,540,738,24,37,1602,1482,713,769,879,723,802,262,93,47,211,90,99,473,183,146
14,Coventry,14,23,22,40,213,176,95,82,247,282,127,79,25,51,3,1,34,36,63,-27,19,15,38,4,7,8,4,3,12,8,10,20
15,Crystal Palace,193,214,189,283,2056,1725,726,600,1993,2108,928,801,273,301,7,8,387,382,497,-115,211,176,346,57,40,75,43,47,84,100,87,159
16,Derby,55,93,35,118,536,398,257,205,769,788,268,209,97,114,2,4,83,90,211,-121,58,25,114,14,16,27,5,10,42,19,26,69
17,Everton,636,440,425,574,5354,4136,2487,1913,4673,4933,2509,1910,573,658,33,39,1148,1061,1014,47,702,446,802,201,99,102,108,122,170,309,221,272
18,Fulham,368,343,245,447,3281,2577,1650,1245,3128,3318,1469,1171,357,441,23,18,623,613,790,-177,410,213,548,116,62,95,41,90,144,157,152,239
19,Huddersfield,19,35,19,50,287,251,76,86,264,313,133,97,33,53,4,1,47,38,85,-47,28,19,54,7,7,13,4,7,16,11,14,29
20,Hull,107,145,74,178,1106,896,438,343,1180,1148,459,388,143,187,12,12,171,181,323,-142,111,60,190,29,24,42,12,24,59,41,48,101
21,Ipswich,51,39,47,67,528,365,261,154,382,478,268,162,25,47,1,2,102,98,106,-8,60,42,76,17,9,12,12,6,20,29,15,32
22,Leeds,164,158,155,191,1548,1179,665,542,1594,1574,718,546,206,241,6,13,311,319,349,-30,162,149,228,44,30,40,43,20,51,87,50,91
23,Leicester,285,247,255,302,2376,1925,932,775,2105,2255,1098,926,242,336,12,21,512,540,549,-9,298,214,384,82,52,58,56,46,90,138,98,148
24,Liverpool,789,303,648,471,6877,5359,3103,2507,4090,4555,2926,2273,407,648,15,29,1513,1437,774,663,854,659,802,251,101,48,189,92,121,440,193,169
25,Man City,794,356,599,470,5996,5007,2754,2254,4151,4430,2821,2147,484,695,25,36,1356,1393,826,567,773,583,764,236,65,81,164,91,127,400,156,208
26,Man United,839,309,658,438,6547,5062,3190,2474,4357,4636,2798,2274,529,715,13,36,1630,1497,747,750,906,724,802,279,69,53,208,100,93,487,169,146
27,Middlesbrough,251,232,163,271,2236,1697,1117,838,2314,2563,1071,732,272,344,12,20,432,414,503,-89,270,162,380,71,57,62,36,54,100,107,111,162
28,Newcastle,527,444,373,612,4867,3520,2252,1620,4277,4264,2157,1607,512,638,27,44,928,900,1056,-156,583,345,726,163,94,107,85,90,187,248,184,294
29,Norwich,155,199,94,263,1548,1222,650,471,1344,1403,661,538,184,195,5,9,231,249,462,-213,155,76,254,40,35,52,15,31,81,55,66,133
30,Portsmouth,184,159,108,221,1826,1230,988,628,1691,1756,839,560,194,217,12,8,302,292,380,-88,196,106,266,54,34,45,25,31,77,79,65,122
31,QPR,60,77,55,122,843,649,356,304,602,618,285,259,87,104,9,6,92,115,199,-84,63,29,114,15,18,24,7,8,42,22,26,66
32,Reading,71,78,65,108,570,503,297,243,583,634,382,325,65,81,5,4,119,136,186,-50,81,38,114,23,12,22,9,11,37,32,23,59
33,Sheffield United,51,60,29,82,565,425,232,155,594,608,305,190,87,105,2,4,100,80,142,-62,63,37,102,18,9,24,9,10,32,27,19,56
34,Southampton,371,325,276,431,3561,3008,1435,1208,3088,3277,1531,1383,339,417,22,16,653,647,756,-109,389,264,536,103,80,84,64,72,133,167,152,217
35,Stoke,248,213,150,312,2181,1700,854,646,2191,2278,1002,710,317,371,14,16,457,398,525,-127,297,160,380,81,54,55,35,55,100,116,109,155
36,Sunderland,288,336,232,459,3206,2484,1476,1139,3211,3327,1437,1114,448,522,17,34,520,520,795,-275,318,202,532,81,75,110,46,64,156,127,139,266
37,Swansea,179,170,127,213,1647,1317,678,521,1280,1357,724,557,188,182,6,8,312,306,383,-77,190,122,266,51,37,45,31,29,73,82,66,118
38,Tottenham,724,410,544,565,6140,4681,2963,2217,4416,4581,2621,2062,524,690,19,37,1316,1268,975,293,783,533,802,233,84,82,144,101,158,377,185,240
39,Watford,132,180,99,201,1407,1124,462,392,1438,1476,580,515,229,180,11,11,222,231,381,-150,131,91,232,33,32,51,23,22,71,56,54,122
40,West Brom,295,361,215,411,2934,2428,1279,1043,2788,2859,1358,1042,359,410,13,22,490,510,772,-262,294,196,494,76,66,105,41,73,133,117,139,238
41,West Ham,492,451,368,562,4433,3512,1952,1494,3934,3932,1982,1587,542,630,17,36,849,860,1013,-153,510,339,688,142,84,119,83,90,170,225,174,289
42,Wigan,169,215,147,267,1986,1602,1024,841,1804,1886,870,638,229,289,9,18,331,316,482,-166,189,142,304,48,45,59,37,31,84,85,76,143
43,Wolves,154,208,128,219,1634,1332,717,583,1471,1539,767,669,206,234,6,10,290,282,427,-145,165,125,270,44,33,58,29,38,68,73,71,126

In [34]:
y20 = y20.groupby('Team').sum().reset_index()

In [35]:
# seasonresults = seasonresults.sort_values(['Points'], axis = 0, ascending = False).reset_index(drop=True)
y20.sort_values(["totalpoints"],axis=0,ascending=False)

,Team,HGS,HGC,AGS,AGC,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,totalpoints,TGS,TGC,GD,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
26,Man United,839,309,658,438,6547,5062,3190,2474,4357,4636,2798,2274,529,715,13,36,1630,1497,747,750,906,724,802,279,69,53,208,100,93,487,169,146
13,Chelsea,838,331,644,382,6579,5417,3061,2469,4399,4562,2721,2256,540,738,24,37,1602,1482,713,769,879,723,802,262,93,47,211,90,99,473,183,146
0,Arsenal,853,353,650,478,6355,4939,3163,2376,4345,4418,2956,2097,551,677,24,46,1545,1503,831,672,888,657,802,268,84,50,184,105,111,452,189,161
24,Liverpool,789,303,648,471,6877,5359,3103,2507,4090,4555,2926,2273,407,648,15,29,1513,1437,774,663,854,659,802,251,101,48,189,92,121,440,193,169
25,Man City,794,356,599,470,5996,5007,2754,2254,4151,4430,2821,2147,484,695,25,36,1356,1393,826,567,773,583,764,236,65,81,164,91,127,400,156,208
38,Tottenham,724,410,544,565,6140,4681,2963,2217,4416,4581,2621,2062,524,690,19,37,1316,1268,975,293,783,533,802,233,84,82,144,101,158,377,185,240
17,Everton,636,440,425,574,5354,4136,2487,1913,4673,4933,2509,1910,573,658,33,39,1148,1061,1014,47,702,446,802,201,99,102,108,122,170,309,221,272
28,Newcastle,527,444,373,612,4867,3520,2252,1620,4277,4264,2157,1607,512,638,27,44,928,900,1056,-156,583,345,726,163,94,107,85,90,187,248,184,294
1,Aston Villa,453,421,406,571,4227,3609,1918,1703,4190,4586,2182,1766,502,683,25,23,875,859,992,-133,497,378,710,130,107,118,93,99,163,223,206,281
41,West Ham,492,451,368,562,4433,3512,1952,1494,3934,3932,1982,1587,542,630,17,36,849,860,1013,-153,510,339,688,142,84,119,83,90,170,225,174,289
34,Southampton,371,325,276,431,3561,3008,1435,1208,3088,3277,1531,1383,339,417,22,16,653,647,756,-109,389,264,536,103,80,84,64,72,133,167,152,217
18,Fulham,368,343,245,447,3281,2577,1650,1245,3128,3318,1469,1171,357,441,23,18,623,613,790,-177,410,213,548,116,62,95,41,90,144,157,152,239
3,Blackburn,289,239,229,353,2645,2000,1343,1047,2886,2848,1206,1036,342,411,23,27,530,518,592,-74,317,213,418,86,59,64,54,51,104,140,110,168
36,Sunderland,288,336,232,459,3206,2484,1476,1139,3211,3327,1437,1114,448,522,17,34,520,520,795,-275,318,202,532,81,75,110,46,64,156,127,139,266
23,Leicester,285,247,255,302,2376,1925,932,775,2105,2255,1098,926,242,336,12,21,512,540,549,-9,298,214,384,82,52,58,56,46,90,138,98,148
5,Bolton,278,260,217,353,2787,2003,1546,1010,2617,2765,1288,970,296,428,17,19,506,495,613,-118,306,200,418,81,63,65,51,47,111,132,110,176
40,West Brom,295,361,215,411,2934,2428,1279,1043,2788,2859,1358,1042,359,410,13,22,490,510,772,-262,294,196,494,76,66,105,41,73,133,117,139,238
35,Stoke,248,213,150,312,2181,1700,854,646,2191,2278,1002,710,317,371,14,16,457,398,525,-127,297,160,380,81,54,55,35,55,100,116,109,155
27,Middlesbrough,251,232,163,271,2236,1697,1117,838,2314,2563,1071,732,272,344,12,20,432,414,503,-89,270,162,380,71,57,62,36,54,100,107,111,162
15,Crystal Palace,193,214,189,283,2056,1725,726,600,1993,2108,928,801,273,301,7,8,387,382,497,-115,211,176,346,57,40,75,43,47,84,100,87,159
42,Wigan,169,215,147,267,1986,1602,1024,841,1804,1886,870,638,229,289,9,18,331,316,482,-166,189,142,304,48,45,59,37,31,84,85,76,143
12,Charlton,179,178,122,208,1436,1087,772,552,1639,1644,731,619,158,180,13,8,325,301,386,-85,195,130,266,54,33,46,31,37,65,85,70,111
37,Swansea,179,170,127,213,1647,1317,678,521,1280,1357,724,557,188,182,6,8,312,306,383,-77,190,122,266,51,37,45,31,29,73,82,66,118
22,Leeds,164,158,155,191,1548,1179,665,542,1594,1574,718,546,206,241,6,13,311,319,349,-30,162,149,228,44,30,40,43,20,51,87,50,91
30,Portsmouth,184,159,108,221,1826,1230,988,628,1691,1756,839,560,194,217,12,8,302,292,380,-88,196,106,266,54,34,45,25,31,77,79,65,122
2,Birmingham,162,140,111,220,1365,1064,707,549,1634,1687,748,565,191,241,13,14,301,273,360,-87,196,105,266,50,46,37,23,36,74,73,82,111
43,Wolves,154,208,128,219,1634,1332,717,583,1471,1539,767,669,206,234,6,10,290,282,427,-145,165,125,270,44,33,58,29,38,68,73,71,126
10,Burnley,138,173,119,235,1514,1277,532,452,1406,1433,656,536,204,239,0,8,277,257,408,-151,169,108,270,45,34,56,25,33,77,70,67,133
29,Norwich,155,199,94,263,1548,1222,650,471,1344,1403,661,538,184,195,5,9,231,249,462,-213,155,76,254,40,35,52,15,31,81,55,66,133
39,Watford,132,180,99,201,1407,1124,462,392,1438,1476,580,515,229,180,11,11,222,231,381,-150,131,91,232,33,32,51,23,22,71,56,54,122
6,Bournemouth,113,126,83,135,1002,824,338,272,715,735,451,399,122,113,5,4,181,196,261,-65,107,74,156,29,20,30,19,17,41,48,37,71
9,Brighton,94,92,72,112,1024,812,289,278,852,869,424,341,136,104,4,10,180,166,204,-38,104,76,156,24,32,21,18,22,39,42,54,60
20,Hull,107,145,74,178,1106,896,438,343,1180,1148,459,388,143,187,12,12,171,181,323,-142,111,60,190,29,24,42,12,24,59,41,48,101
32,Reading,71,78,65,108,570,503,297,243,583,634,382,325,65,81,5,4,119,136,186,-50,81,38,114,23,12,22,9,11,37,32,23,59
21,Ipswich,51,39,47,67,528,365,261,154,382,478,268,162,25,47,1,2,102,98,106,-8,60,42,76,17,9,12,12,6,20,29,15,32
33,Sheffield United,51,60,29,82,565,425,232,155,594,608,305,190,87,105,2,4,100,80,142,-62,63,37,102,18,9,24,9,10,32,27,19,56
31,QPR,60,77,55,122,843,649,356,304,602,618,285,259,87,104,9,6,92,115,199,-84,63,29,114,15,18,24,7,8,42,22,26,66
16,Derby,55,93,35,118,536,398,257,205,769,788,268,209,97,114,2,4,83,90,211,-121,58,25,114,14,16,27,5,10,42,19,26,69
19,Huddersfield,19,35,19,50,287,251,76,86,264,313,133,97,33,53,4,1,47,38,85,-47,28,19,54,7,7,13,4,7,16,11,14,29
8,Brentford,22,21,26,35,233,209,77,77,187,184,88,71,29,32,2,1,46,48,56,-8,24,22,38,7,3,9,6,4,9,13,7,18
11,Cardiff,32,50,15,54,358,247,105,72,257,242,157,110,42,32,0,2,44,47,104,-57,33,11,54,9,6,13,2,5,19,11,11,32
4,Blackpool,30,37,25,41,253,193,134,101,216,187,94,92,22,25,0,2,39,55,78,-23,20,19,38,5,5,9,5,4,10,10,9,19
14,Coventry,14,23,22,40,213,176,95,82,247,282,127,79,25,51,3,1,34,36,63,-27,19,15,38,4,7,8,4,3,12,8,10,20
7,Bradford,20,29,10,41,221,150,101,73,255,262,108,71,27,30,0,1,26,30,70,-40,19,7,38,4,7,8,1,4,14,5,11,22

In [36]:
# ordering the columns i want to show from this big df
discols =['Team','HGS','HGC','AGS','AGC','TGS','TGC','GD','totalpoints','homepoints','awaypoints','gamesplayed','homewin','homedraw','homeloss','awaywin','awaydraw','awayloss','winsagg','drawsagg','lossagg']

In [37]:
# sorting the big df by points
distable = y20[discols].sort_values(["totalpoints"],axis=0,ascending=False)

In [38]:
distable

,Team,HGS,HGC,AGS,AGC,TGS,TGC,GD,totalpoints,homepoints,awaypoints,gamesplayed,homewin,homedraw,homeloss,awaywin,awaydraw,awayloss,winsagg,drawsagg,lossagg
26,Man United,839,309,658,438,1497,747,750,1630,906,724,802,279,69,53,208,100,93,487,169,146
13,Chelsea,838,331,644,382,1482,713,769,1602,879,723,802,262,93,47,211,90,99,473,183,146
0,Arsenal,853,353,650,478,1503,831,672,1545,888,657,802,268,84,50,184,105,111,452,189,161
24,Liverpool,789,303,648,471,1437,774,663,1513,854,659,802,251,101,48,189,92,121,440,193,169
25,Man City,794,356,599,470,1393,826,567,1356,773,583,764,236,65,81,164,91,127,400,156,208
38,Tottenham,724,410,544,565,1268,975,293,1316,783,533,802,233,84,82,144,101,158,377,185,240
17,Everton,636,440,425,574,1061,1014,47,1148,702,446,802,201,99,102,108,122,170,309,221,272
28,Newcastle,527,444,373,612,900,1056,-156,928,583,345,726,163,94,107,85,90,187,248,184,294
1,Aston Villa,453,421,406,571,859,992,-133,875,497,378,710,130,107,118,93,99,163,223,206,281
41,West Ham,492,451,368,562,860,1013,-153,849,510,339,688,142,84,119,83,90,170,225,174,289
34,Southampton,371,325,276,431,647,756,-109,653,389,264,536,103,80,84,64,72,133,167,152,217
18,Fulham,368,343,245,447,613,790,-177,623,410,213,548,116,62,95,41,90,144,157,152,239
3,Blackburn,289,239,229,353,518,592,-74,530,317,213,418,86,59,64,54,51,104,140,110,168
36,Sunderland,288,336,232,459,520,795,-275,520,318,202,532,81,75,110,46,64,156,127,139,266
23,Leicester,285,247,255,302,540,549,-9,512,298,214,384,82,52,58,56,46,90,138,98,148
5,Bolton,278,260,217,353,495,613,-118,506,306,200,418,81,63,65,51,47,111,132,110,176
40,West Brom,295,361,215,411,510,772,-262,490,294,196,494,76,66,105,41,73,133,117,139,238
35,Stoke,248,213,150,312,398,525,-127,457,297,160,380,81,54,55,35,55,100,116,109,155
27,Middlesbrough,251,232,163,271,414,503,-89,432,270,162,380,71,57,62,36,54,100,107,111,162
15,Crystal Palace,193,214,189,283,382,497,-115,387,211,176,346,57,40,75,43,47,84,100,87,159
42,Wigan,169,215,147,267,316,482,-166,331,189,142,304,48,45,59,37,31,84,85,76,143
12,Charlton,179,178,122,208,301,386,-85,325,195,130,266,54,33,46,31,37,65,85,70,111
37,Swansea,179,170,127,213,306,383,-77,312,190,122,266,51,37,45,31,29,73,82,66,118
22,Leeds,164,158,155,191,319,349,-30,311,162,149,228,44,30,40,43,20,51,87,50,91
30,Portsmouth,184,159,108,221,292,380,-88,302,196,106,266,54,34,45,25,31,77,79,65,122
2,Birmingham,162,140,111,220,273,360,-87,301,196,105,266,50,46,37,23,36,74,73,82,111
43,Wolves,154,208,128,219,282,427,-145,290,165,125,270,44,33,58,29,38,68,73,71,126
10,Burnley,138,173,119,235,257,408,-151,277,169,108,270,45,34,56,25,33,77,70,67,133
29,Norwich,155,199,94,263,249,462,-213,231,155,76,254,40,35,52,15,31,81,55,66,133
39,Watford,132,180,99,201,231,381,-150,222,131,91,232,33,32,51,23,22,71,56,54,122
6,Bournemouth,113,126,83,135,196,261,-65,181,107,74,156,29,20,30,19,17,41,48,37,71
9,Brighton,94,92,72,112,166,204,-38,180,104,76,156,24,32,21,18,22,39,42,54,60
20,Hull,107,145,74,178,181,323,-142,171,111,60,190,29,24,42,12,24,59,41,48,101
32,Reading,71,78,65,108,136,186,-50,119,81,38,114,23,12,22,9,11,37,32,23,59
21,Ipswich,51,39,47,67,98,106,-8,102,60,42,76,17,9,12,12,6,20,29,15,32
33,Sheffield United,51,60,29,82,80,142,-62,100,63,37,102,18,9,24,9,10,32,27,19,56
31,QPR,60,77,55,122,115,199,-84,92,63,29,114,15,18,24,7,8,42,22,26,66
16,Derby,55,93,35,118,90,211,-121,83,58,25,114,14,16,27,5,10,42,19,26,69
19,Huddersfield,19,35,19,50,38,85,-47,47,28,19,54,7,7,13,4,7,16,11,14,29
8,Brentford,22,21,26,35,48,56,-8,46,24,22,38,7,3,9,6,4,9,13,7,18
11,Cardiff,32,50,15,54,47,104,-57,44,33,11,54,9,6,13,2,5,19,11,11,32
4,Blackpool,30,37,25,41,55,78,-23,39,20,19,38,5,5,9,5,4,10,10,9,19
14,Coventry,14,23,22,40,36,63,-27,34,19,15,38,4,7,8,4,3,12,8,10,20
7,Bradford,20,29,10,41,30,70,-40,26,19,7,38,4,7,8,1,4,14,5,11,22

In [39]:
distable['win%'] = round((distable['winsagg']/distable['gamesplayed']*100),1)
distable['draw%'] = round((distable['drawsagg']/distable['gamesplayed']*100),1)
distable['loss%'] = round((distable['lossagg']/distable['gamesplayed']*100),1)
# inbigfunc doesnt work in big func have to do after the groupby/sums

In [40]:
Leic = distable.loc[distable['Team'].isin(['Leicester'])]

In [41]:
Leic[['Team','totalpoints','gamesplayed','GD','win%','draw%','loss%','homepoints','awaypoints','winsagg','drawsagg','lossagg']]

,Team,totalpoints,gamesplayed,GD,win%,draw%,loss%,homepoints,awaypoints,winsagg,drawsagg,lossagg
23,Leicester,512,384,-9,35.9,25.5,38.5,298,214,138,98,148

# HYPTEST

Question: does the home team win over 50% of games in the English Premier League

In [42]:
# distable.head()

In [43]:
modelist = [y0001,y0102,y0203,y0304,y0405,y0506,y0607,y0708,y0809,y0910,y1011,y1112,y1213,y1314,y1415,y1516,y1617,y1718,y1819,y1920,y2021,y2122]

In [44]:
hyp = pd.concat(modelist, axis=0)

In [45]:
hyp['FTR'].value_counts()

H    3667
A    2331
D    2022
Name: FTR, dtype: int64

In [46]:
# hyp['FTR'] = hyp['FTR'].map({'H': 2, 'D': 1, 'A': 0})
(3667 + 2331 + 2022) / 2

4010.0

In [47]:
# we select a value for alpha of 0.05 (p-value threshold) #significance level 
# Two-sided test:
# Null hypothesis or H0: 
# Alternative hyp or H1: 


# One-sided test:
# Null hypothesis or H0: 
# city points is <= united points average 
# Alternative hyp or H1: 
# united has more points on average 
from scipy.stats import ttest_1samp
from scipy.stats import ttest_ind
stat, pval = ttest_1samp(city['totalpoints'], 74.09)
# two sided test is h0 is = to, h1 is unequal to(lower or higher), two ways to be wrong 
# one sided test, h0 greater than or equal to, h1 is less than, one way to be wrong 
print(stat)
print(pval)

NameError: name 'city' is not defined

In [ ]:
# man united has a higher average points than city

In [ ]:
#  mean points of one team will be higher than the other teams?
# pick city, see if the mean points of specific team is higher than mean of other top5 teams
# 1samp first is mean of city points,

In [ ]:
# first columns df of city points all through seasons
# mean of other teams points

In [ ]:
winpttable.head()

In [ ]:
city = winpttable[winpttable['Team'] == 'Man City']

In [ ]:
united = winpttable[winpttable['Team'] == 'Man United']

In [ ]:
united['totalpoints'].mean()

In [ ]:
# h0 the top 6 will have a higher average win% than the rest of all the teams involved in EPL since 2000
# h1 the other roughly 40 teams will have a higher average win%

In [ ]:
stat2, pval2 = ttest_1samp(top6['win%'], 27.93)

In [ ]:
print(stat2)
print(pval2)

In [ ]:
# h0, the top6 have a higher average win% across all seasons since 2000

In [ ]:
# make a hyp test for city vs liverpool 2018/19?

# Top 6 vs the rest?

In [ ]:
# distable.loc[[26,13,0,24,25,39]]

In [ ]:
# distable.loc[[17,29,42,1,35,18,23,3,37,5,41,36,15,28,44,43,12,10,38,22,31,2,40,30,6,9,20,33,34,21,32,16,11,19,27,8,4,14,7]]

In [ ]:
# df.loc[df['col1'].isin([value1, value2, value3, ...])]

In [ ]:
# distable['winsagg'] = distable['homewin']+distable['awaywin']
# distable['drawsagg'] = distable['homedraw']+distable['awaydraw']
# distable['lossagg'] = distable['homeloss']+distable['awayloss']
# inbigfunc

In [ ]:
# distable.head()

In [ ]:
# ratios? wins/total*100 = %

In [ ]:
distable.head()

In [ ]:
top6 = distable.loc[distable['Team'].isin(['Man United', 'Chelsea', 'Arsenal', 'Man City', 'Liverpool', 'Tottenham'])]

In [ ]:
nottop6 = distable.loc[distable['Team'].isin(['Man United', 'Chelsea', 'Arsenal', 'Man City', 'Liverpool', 'Tottenham'])==False]

In [ ]:
top6

In [ ]:
nottop6

In [ ]:
top6[['Team','totalpoints','gamesplayed','GD','win%','draw%','loss%','homepoints','awaypoints','winsagg','drawsagg','lossagg']]

# Stats for presenting

In [ ]:
distable

In [ ]:
winnersdic = {
             'ManUnited':7,
             'ManCity':6,
             'Chelsea':5,
             'Arsenal':2,
             'Leicester':1,
             'Liverpool':1}

In [ ]:
winnersdic

In [ ]:
presentings = distable
presentings

In [ ]:
presentings['gamesplayed'].sum()

In [ ]:
presentings['winsagg'].sum()

In [ ]:
presentings['drawsagg'].sum()

In [ ]:
presentings['lossagg'].sum()

In [ ]:
def winpct(df):
    
    df['win%'] = round((df['winsagg']/df['gamesplayed']*100),1)
    df['draw%'] = round((df['drawsagg']/df['gamesplayed']*100),1)
    df['loss%'] = round((df['lossagg']/df['gamesplayed']*100),1)

    return(df)

In [ ]:
s0001 = winpct(sr0001)
s0102 = winpct(sr0102)
s0203 = winpct(sr0203)
s0304 = winpct(sr0304)
s0405 = winpct(sr0405)
s0506 = winpct(sr0506)
s0607 = winpct(sr0607)
s0708 = winpct(sr0708)
s0809 = winpct(sr0809)
s0910 = winpct(sr0910)
s1011 = winpct(sr1011)
s1112 = winpct(sr1112)
s1213 = winpct(sr1213)
s1314 = winpct(sr1314)
s1415 = winpct(sr1415)
s1516 = winpct(sr1516)
s1617 = winpct(sr1617)
s1718 = winpct(sr1718)
s1819 = winpct(sr1819)
s1920 = winpct(sr1920)
s2021 = winpct(sr2021)
s2122 = winpct(sr2122)

In [ ]:
winlist = [s0001,
s0102,
s0203,
s0304,
s0405,
s0506,
s0607,
s0708,
s0809,
s0910,
s1011,
s1112,
s1213,
s1314,
s1415,
s1516,
s1617,
s1718,
s1819,
s1920,
s2021,
s2122]

In [ ]:
bigtablewp = pd.concat(winlist,axis=0).reset_index(drop=True)

In [ ]:
bigtablewp

In [ ]:
# bigtablewp.sort_values(["win%"],axis=0,ascending=False)

In [ ]:
winpttable = bigtablewp[['Team','totalpoints','TGC','TGC','GD','win%','draw%','loss%','homepoints','awaypoints','gamesplayed','homewin','homedraw','homeloss','awaywin','awayloss','winsagg','drawsagg','lossagg']].sort_values(["win%"],axis=0,ascending=False)

In [ ]:
winpttable

In [ ]:
Leic2 = s1516.loc[s1516['Team'].isin(['Leicester'])]

In [ ]:
Leic2[['Team','totalpoints','gamesplayed','GD','win%','draw%','loss%','homepoints','awaypoints','winsagg','drawsagg','lossagg']]

In [ ]:
# y20.sort_values(["totalpoints"],axis=0,ascending=False)

In [ ]:
winpttable.sort_Values(['win%'],axis=0, ascending=False)

In [ ]:
# predicting home wins vs non home wins
# stat analysis into this? make some graphs?
# nfc

# new question????

In [ ]:
# doesnt work 
# pd.set_option('display.max_rows', None)
# test = test.sort_values(['Points'], axis=0, ascending=False)
# test

In [ ]:
# group by home team for total goal scored at home
# same away 
# add togetehr 

# date change 

# group by home team, home points
# group by away team, away points
# add together 
# = points total 

# home table/df 
# away table/df

# key column?

# if fthg > ftag ht win and assign total goals

# loop using the first 380 
# if fthg > ftag 

# can it do it without the score ?

# total shots, goal, yc, rc, posts, on target, off target, offsides etc

# wins draws losses columns?

# is tehre relationship between results / points
# home goals/wins to points
# home wins 50%?
# home gmae adv ?

In [ ]:
# new question 
# is there a quanitfiable home team advantage in the Premier league 
# home wins/draw/losses count

# goals scored and conceded

# games played

# won drew loss x games home/away

In [ ]:
# if away win append 1 to the away list
# append 0 home list
# append 0 draw list

# change data to model

In [ ]:
# need to use games not season results?

In [ ]:
import pandas as pd

In [ ]:
modelist = [y0001,y0102,y0203,y0304,y0405,y0506,y0607,y0708,y0809,y0910,y1011,y1112,y1213,y1314,y1415,y1516,y1617,y1718,y1819,y1920,y2021,y2122]

In [ ]:
bigtable = pd.concat(modelist, axis=0)

In [ ]:
# get everything into uniform cols
# columnsreq = [['Date','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
#  'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]

In [ ]:
bigtable = bigtable[['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]

In [ ]:
bigtable

In [ ]:
# def only_hw(string):
#     if string == 'H':
#         return 'H'
#     else:
#         return 'NH'
    
# bigtable['FTR'] = bigtable.FTR.apply(only_hw)

In [ ]:
bigtable

In [ ]:
# bigtable.loc[bigtable['FTR'].str.contains('H'),'FTR']=0

# bigtable.loc[bigtable['FTR'].str.contains('A'),'FTR']=1

# bigtable.loc[bigtable['FTR'].str.contains('D'),'FTR']=1

In [ ]:
bigtable['FTR'] = bigtable['FTR'].map({'H': 1, 'D': 0, 'A': 0})
# 1 is home win, 0 is not home win

In [ ]:
# fthg ag out

In [ ]:
bigtable.groupby(['FTR']).sum().plot(kind='pie')

In [ ]:
# plt.figure(figsize=(22,14))
# bigtable.HomeTeam.value_counts().plot(kind='pie', y='FTR', autopct='%1.1f%%')
# plt.show

# home wins = 1
# not home wins = 0

# not what i want
# not very useful either

# Models

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# linear regression?
# logistic?
# MLPregressor?
# Random forest?
# Knn? maybe no 
# xgboost?

In [ ]:

y = bigtable['FTR']
X = bigtable.drop(['FTR','HomeTeam','AwayTeam', 'FTHG', 'FTAG'],axis=1)

In [ ]:
# take out columns, FTHG/FTAG was giving models the answer, have to remove

In [ ]:
plt.figure(figsize=(20,10)) 
sns.heatmap(bigtable.corr(), annot= True)

In [ ]:
# htag,hthg,hs,as,hst,ast have high correlations

In [ ]:
# pd.plotting.scatter_matrix(X, figsize=(20,10))

In [ ]:
# plot ftr (target) against ast/hst

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
lm = linear_model.LinearRegression()
lm.fit(X_train, y_train)
print('score', lm.score(X_train,y_train))

In [ ]:
# score wont chnage after scaling, the ranges arent big enough

In [ ]:


Xnumtrain = X_train.select_dtypes(np.number)
Xnumtest = X_test.select_dtypes(np.number)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(Xnumtrain)
Xnumtrainscale = transformer.transform(Xnumtrain)
Xnumtestscale = transformer.transform(Xnumtest)

In [ ]:
X_train_processed = pd.DataFrame(Xnumtrainscale, columns=Xnumtrain.columns)

In [ ]:
X_test_processed = pd.DataFrame(Xnumtestscale, columns=Xnumtest.columns)

In [ ]:
# X_train_processed = pd.DataFrame((Xnumtrain,Xcattrain),axis=1)
# X_test_processed = pd.DataFrame((Xnumtest,Xcattest),axis=1)

In [ ]:
X_train_processed

In [ ]:
X_test_processed

# Linear regression

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
lm = linear_model.LinearRegression()
lm.fit(X_train_processed, y_train)
print('score', lm.score(X_train_processed,y_train))

# Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_processed, y_train)

In [ ]:
Y_predlog = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, Y_predlog)

In [ ]:
sns.heatmap(cm, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test, Y_predlog))

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

KNN = KNeighborsRegressor(n_neighbors=3)
KNN.fit(X_train_processed, y_train)

In [ ]:
score_train = KNN.score(X_train_processed, y_train)
score_train          #R2 score

In [ ]:
score = KNN.score(X_test_processed, y_test)
score                #R2 score

In [ ]:
KNN2 = KNeighborsRegressor(n_neighbors=2)
KNN2.fit(X_train_processed, y_train)

In [ ]:
score_train2 = KNN2.score(X_train_processed, y_train)
score_train2          #R2 score

In [ ]:
score2 = KNN2.score(X_test_processed, y_test)
score2                #R2 score

In [ ]:
# closest rows in stats could have different end results 
# (high shots team vs low bloc defenders = huge shots but no goals)

# teams with identical enough game stats having opposite end results, very possible
# 8000+games checking neighbours probably not as useful for predicting

# SVC model

In [ ]:
# SVC, or Support Vector Classifier, is a supervised machine learning algorithm typically 
# used for classification tasks. 
# SVC works by mapping data points to a high-dimensional space and then finding the optimal hyperplane 
# that divides the data into two classes.

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state = 0)
classifier.fit(X_train_processed, y_train)

In [ ]:
Y_predsvc = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix
cmsvc = confusion_matrix(y_test, Y_predsvc)

In [ ]:
sns.heatmap(cmsvc, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test, Y_predsvc))

# RandomForestClassifier

In [ ]:
# Random forest is a Supervised Machine Learning Algorithm that is used widely in Classification 
# and Regression problems. It builds decision trees on different samples and takes their majority 
# vote for classification and average in case of regression.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_processed, y_train)

In [ ]:
#predicting result
Y_predrfc1 = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc1 = confusion_matrix(y_test, Y_predrfc1)

In [ ]:
sns.heatmap(cmrfc1, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test, Y_predrfc1))

In [ ]:
# change parameters to compare results

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(criterion='gini', 
                             n_estimators=700,
                             min_samples_split=10,
                             min_samples_leaf=1,
                             max_features='sqrt',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1)
classifier.fit(X_train_processed, y_train)

In [ ]:
#predicting result
Y_predrfc = classifier.predict(X_test_processed)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc = confusion_matrix(y_test, Y_predrfc)

In [ ]:
sns.heatmap(cmrfc, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test, Y_predrfc))

# XGBOOST

In [ ]:
# XGBoost, which stands for Extreme Gradient Boosting, is a scalable,
# distributed gradient-boosted decision tree (GBDT) machine learning library.
# It provides parallel tree boosting and is the leading machine learning library
# for regression, classification, and ranking problems.

In [ ]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier(seed=82)
classifier.fit(X_train_processed, y_train)

In [ ]:
# Predicting the Test set results
Y_predx = classifier.predict(X_test_processed)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmx = confusion_matrix(y_test, Y_predx)

In [ ]:
sns.heatmap(cmx, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test, Y_predx))

In [ ]:
# can I boost the xgboost?

# MLPregressor

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp=MLPRegressor(random_state=1, max_iter=500)
mlp.fit(X_train_processed, y_train)

In [ ]:
# Predicting the Test set results
Y_predmlp = classifier.predict(X_test_processed)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmlp = confusion_matrix(y_test, Y_predmlp)

In [ ]:
sns.heatmap(cmlp, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test, Y_predmlp))

# Can we predict a home win?

In [ ]:
# in general with the more aacurate scoring models we can predict a home win around 70% of the time

In [ ]:
# is this useful? or interesting?

# Models with half time goals ?

In [ ]:
# modelist = [y0001,y0102,y0203,y0304,y0405,y0506,y0607,y0708,y0809,y0910,y1011,y1112,y1213,y1314,y1415,y1516,y1617,y1718,y1819,y1920,y2021,y2122]

In [ ]:
secondmodel = pd.concat(modelist, axis=0)

In [ ]:
secondmodel = secondmodel[['HomeTeam', 'AwayTeam', 'HTHG', 'HTAG', 'FTR', 'HS', 'AS','HST', 'AST', 'HF', 'AF',
 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]

In [ ]:
secondmodel

In [ ]:
secondmodel['FTR'] = secondmodel['FTR'].map({'H': 1, 'D': 0, 'A': 0})

In [ ]:
secondmodel

In [ ]:
secondmodel.isna().sum()

In [ ]:
secondmodel=secondmodel.dropna()

In [ ]:
secondmodel.isna().sum()

In [ ]:
# weird

# Models again

In [ ]:
# keeping half time goals in to see if it helps the mdoel decide home win/not

In [ ]:

y2 = secondmodel['FTR']
X2 = secondmodel.drop(['FTR','HomeTeam','AwayTeam'],axis=1)

In [ ]:
plt.figure(figsize=(20,10)) 
sns.heatmap(secondmodel.corr(), annot= True)

In [ ]:
from sklearn.model_selection import train_test_split 
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.2, random_state=42)

In [ ]:

Xnumtrain2 = X_train2.select_dtypes(np.number)
Xnumtest2 = X_test2.select_dtypes(np.number)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

transformer = MinMaxScaler().fit(Xnumtrain2)
Xnumtrainscale2 = transformer.transform(Xnumtrain2)
Xnumtestscale2 = transformer.transform(Xnumtest2)

In [ ]:
X_train_processed2 = pd.DataFrame(Xnumtrainscale2, columns=Xnumtrain2.columns)
X_test_processed2 = pd.DataFrame(Xnumtestscale2, columns=Xnumtest2.columns)

In [ ]:
X_train_processed2

In [ ]:
X_test_processed2

# Linear regression

In [ ]:
# first linear regression score was crap so dont do it again
# i dont think its a linear problem anyway

# Logistic

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_processed2, y_train2)

In [ ]:
Y_predlog2 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
cmlog2 = confusion_matrix(y_test2, Y_predlog2)

In [ ]:
sns.heatmap(cmlog2, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predlog2))

# KNN

In [ ]:
# didnt like knn results last time so not doing again

# SVC

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state = 0)
classifier.fit(X_train_processed2, y_train2)

In [ ]:
Y_predsvc2 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix
cmsvc2 = confusion_matrix(y_test2, Y_predsvc2)

In [ ]:
sns.heatmap(cmsvc2, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predsvc2))

# RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_processed2, y_train2)

In [ ]:
#predicting result
Y_predrfc12 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc12 = confusion_matrix(y_test2, Y_predrfc12)

In [ ]:
sns.heatmap(cmrfc12, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predrfc12))

In [ ]:
# parameter fiddling

In [ ]:
from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier = RandomForestClassifier(criterion='gini', 
                             n_estimators=700,
                             min_samples_split=10,
                             min_samples_leaf=1,
                             max_features='sqrt',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1)
classifier.fit(X_train_processed2, y_train2)

In [ ]:
#predicting result
Y_predrfc2 = classifier.predict(X_test_processed2)

In [ ]:
from sklearn.metrics import confusion_matrix
cmrfc2 = confusion_matrix(y_test2, Y_predrfc2)

In [ ]:
sns.heatmap(cmrfc2, annot=True, fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predrfc2))

# XGBOOST

In [ ]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier(seed=82)
classifier.fit(X_train_processed2, y_train2)

In [ ]:
# Predicting the Test set results
Y_predx2 = classifier.predict(X_test_processed2)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmx2 = confusion_matrix(y_test2, Y_predx2)

In [ ]:
sns.heatmap(cmx2, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predx2))

In [ ]:
# scores become slightly better, as the half time result != full time result in many cases, 
# strong enough indicator of who is going to win that the accuracy scores increase a litte bit however

# MLPregressor

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp2=MLPRegressor(random_state=1, max_iter=500)
mlp2.fit(X_train_processed2, y_train2)

In [ ]:
# Predicting the Test set results
Y_predmlp2 = classifier.predict(X_test_processed2)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cmlp2 = confusion_matrix(y_test2, Y_predmlp2)

In [ ]:
sns.heatmap(cmlp2, annot=True,fmt='d')

In [ ]:
print(classification_report(y_test2, Y_predmlp2))

# to csv

In [ ]:
# y6.to_csv('y6.csv', index=False)

In [ ]:
# y20.to_csv('y20.csv', index=False)

In [ ]:
# distable.to_csv('distable.csv', index=False)

In [ ]:
# top6.to_csv('top6.csv', index=False)

In [ ]:
# nottop6.to_csv('nottop6.csv', index=False)

In [ ]:
# bigtable.to_csv('bigtable.csv', index=False)

In [ ]:
# winpttable.to_csv('winpttable.csv', index=False)

In [ ]:
# done already
# I've had to run this workbook a million times 
# dont need to overwrite again

# SQL

In [ ]:
# import pymysql
# from sqlalchemy import create_engine
# import getpass  # To get the password without showing the input

# password = getpass.getpass()

In [ ]:
# # get the data
# connection_string = 'mysql+pymysql://root:' + password + '@localhost/midpro'
# engine = create_engine(connection_string)

In [ ]:
# distable.to_sql('distable', con=engine)
# # do this again

In [ ]:
# y6.to_sql('y6', con=engine)

In [ ]:
# y20.to_sql('y20', con=engine)

In [ ]:
# top6.to_sql('top6', con=engine)

In [ ]:
# nottop6.to_sql('nottop6', con=engine)

In [ ]:
# bigtable.to_sql('bigtable', con=engine)

In [ ]:
# secondmodel.to_sql('secondmodel', con=engine)

In [ ]:
# query = 'select * from distable'
# sqlproof = pd.read_sql_query(query, engine)
# sqlproof.head()

In [ ]:
# done